// /mindmap/content/d8FH8K7n0GE.js
// Deep content — "Live for Something Bigger / Do It Alone, Broke, Tired & Scared (cut court, manifeste)" — Andrew Tate

const CONTENT_d8FH8K7n0GE = {
  id: "d8FH8K7n0GE",
  slug: "live-for-something-bigger",
  title: "Live for Something Bigger (Sacred Duties)",
  speaker: "Andrew Tate",
  format: "monologue motivationnel · manifeste philosophique · litanie 'I believe'",
  word_count: 6800,
  language: "en",

  hook: "You can't escape this fight. The war is here.",
  thesis: "Être un homme, c'est accepter la guerre permanente — contre la Matrice ou contre son propre esprit — et adopter un stoïcisme compétitif où le bonheur cesse d'être une mesure pertinente.",
  key_takeaways: [
    "Deux choix seulement : la guerre contre la Matrice ou la guerre contre son propre esprit — pas d'échappatoire",
    "Refuser de devenir l'ennemi de son propre esprit — 'me and everything inside of me is on the same team'",
    "Substituer l'axe duty/abandon à l'axe happy/sad — le bonheur est une mesure asinine",
    "Ton amour vaut ta compétence — un incapable qui aime, ça ne signifie rien",
    "Vie comme jeu vidéo — level up ton personnage jusqu'à ce que le jeu devienne facile",
    "Le respect > l'amour dans la hiérarchie des besoins masculins (thèse contestable)",
    "Choisir la fierté plutôt que le bonheur — les décisions changent",
    "Le credo 'I believe' — 20+ articles de foi sur les sacred duties de l'homme",
  ],

  chapters: [
    {
      idx: 1,
      title: "Deux choix : guerre Matrice ou guerre self",
      summary: "Ouverture-massue : impossible d'échapper au combat. Soit tu te réveilles et tu combats la Matrice, soit tu acceptes le programme et tu combats ton propre esprit. Pas de troisième option.",
      key_quote: "You can't escape this fight. Everybody watching this is in this fight. The war is here.",
      duration_estimate: "0:00-3:00",
    },
    {
      idx: 2,
      title: "Le bonheur est une mesure asinine",
      summary: "Substitution d'axe : on ne mesure pas la vie d'un homme au bonheur mais au duty. What must be done. Attaque frontale du 'chase happiness' comme le pire piège.",
      key_quote: "Chasing happiness is probably the most asinine thing you can do. It's the easiest way to lose as a man.",
      duration_estimate: "3:00-6:30",
    },
    {
      idx: 3,
      title: "Ton amour = ta compétence",
      summary: "Argument déstabilisant : la valeur de l'amour est proportionnelle à la capacité. Un père incapable qui aime ses enfants = zéro. Pour aimer vraiment, améliore-toi.",
      key_quote: "Your love as a man is directly correlated to your competence and your capabilities.",
      duration_estimate: "6:30-9:30",
    },
    {
      idx: 4,
      title: "Vie comme video game — level up ton character",
      summary: "Métaphore du RPG : la vie est un jeu difficile, monte ton perso jusqu'à ce que ça devienne facile. Ego, high score, all-women, all-Ferraris. Assumer le désir de statut.",
      key_quote: "It's a video game. I want a high score.",
      duration_estimate: "9:30-14:00",
    },
    {
      idx: 5,
      title: "Name a better time to be a man — l'histoire",
      summary: "Questions rhétoriques empilées : Titanic, Napoleon, pyramides, Vienne face aux Mongols. Aucune époque n'a été facile pour les hommes. Seuls les 2% du sommet ont une bonne vie.",
      key_quote: "Name a time in history that was better to be a man. It's always sucked.",
      duration_estimate: "14:00-18:00",
    },
    {
      idx: 6,
      title: "Respect > love + male depression fixable by respect",
      summary: "Substitution : le bonheur masculin vient du respect ressenti, pas de l'amour reçu. La dépression masculine se résout par le respect. Métaphore de la voiture qui dérape jusqu'au crash.",
      key_quote: "Male depression can be fixed with respect.",
      duration_estimate: "18:00-22:00",
    },
    {
      idx: 7,
      title: "Le credo des Sacred Duties",
      summary: "Litanie de 20+ 'I believe' constituant le climax de la vidéo. Credo laïc de la masculinité : protéger, fournir, élever des fils, tenir parole, s'entraîner, poursuivre l'abondance, encourager la fraternité.",
      key_quote: "I believe men have the sacred duty to protect and provide for the important people in their lives.",
      duration_estimate: "22:00-27:00",
    },
    {
      idx: 8,
      title: "Truth is what wins + conquest financière",
      summary: "Passage philosophiquement dangereux : la vérité, c'est ce qui te fait gagner. Puis fermeture sur la conquête financière comme sublimation moderne de la conquête militaire.",
      key_quote: "True and false is adopting the mindset or the strategies which allow you to compete and win. That's what's true.",
      duration_estimate: "27:00-fin",
    },
  ],

  argument_tree: {
    root: {
      claim: "Être un homme = accepter la guerre permanente + stoïcisme compétitif où le bonheur cesse d'être pertinent",
      children: [
        {
          claim: "Deux seules options : combattre la Matrice ou combattre soi-même",
          type: "premise",
          strength: 7,
          evidence: [
            "Anaphore 'in this fight' (quintuple)",
            "L'acceptation du programme = guerre intérieure",
          ],
          children: [
            { claim: "False dichotomy évidente — beaucoup d'hommes vivent hors de cette dichotomie", type: "counter", strength: 8 },
          ],
        },
        {
          claim: "Le bonheur est une mesure asinine pour un homme",
          type: "premise",
          strength: 6,
          evidence: [
            "'What must be done' > 'what makes me happy'",
            "Substitution d'axe duty/abandon",
          ],
          children: [
            { claim: "Vrai comme protocole (agir sans dépendre de l'humeur) — faux comme théorie (le bien-être prédit la performance long-terme)", type: "counter", strength: 8 },
          ],
        },
        {
          claim: "Ton amour n'a de valeur que si tu es capable",
          type: "premise",
          strength: 6,
          evidence: [
            "Un père incapable ne peut ni nourrir ni protéger",
            "Love = competence × capabilities",
          ],
          children: [
            { claim: "Confusion entre soutien matériel et lien d'attachement — un enfant aimé dans la pauvreté vit mieux qu'un enfant riche non aimé", type: "counter", strength: 9 },
          ],
        },
        {
          claim: "La vie est un video game — level up ton personnage",
          type: "analogy",
          strength: 8,
          evidence: [
            "Chaque skill est acquis, pas donné",
            "Le jeu devient facile à haut niveau",
          ],
          children: [
            { claim: "Métaphore puissante (agentivité, progression) — utile même sans souscrire à toute la doctrine", type: "meta", strength: 9 },
          ],
        },
        {
          claim: "Le respect > l'amour dans la hiérarchie masculine",
          type: "premise",
          strength: 5,
          evidence: [
            "Male depression fixable by respect",
            "Woman respect requires other women desire",
          ],
          children: [
            { claim: "Vrai chez les jeunes hommes en perte de statut — faux comme théorie universelle des besoins masculins", type: "nuance", strength: 8 },
          ],
        },
        {
          claim: "Les hommes ont des sacred duties (credo I believe)",
          type: "manifeste",
          strength: 8,
          evidence: [
            "Litanie de 20+ 'I believe'",
            "Effet liturgique cumulé",
          ],
          children: [
            { claim: "Mélange défendable (tenir parole, protéger enfants) et discutable (raise strong sons — pas de filles ?)", type: "nuance", strength: 8 },
          ],
        },
      ],
    },
  },

  quotes: [
    {
      text: "You can't escape this fight. Everybody watching this is in this fight. I'm in this fight. You're in this fight. We're all in this fight. The war is here.",
      context: "Ouverture-massue — anaphore quintuple",
      tags: ["combat", "ouverture", "anaphore"],
      rhetorical_device: "Anaphore quintuple sur 'in this fight'",
      power_score: 10,
      chapter_idx: 1,
      highlight_words: ["can't escape", "in this fight", "war is here"],
    },
    {
      text: "You either wake up and you are now in battle against the matrix itself or you accept the programming. When you accept the programming, the battle doesn't end because now you're in a battle against your own mind.",
      context: "Les deux options exposées",
      tags: ["choix-binaire", "matrice", "mental"],
      rhetorical_device: "Dichotomie forcée",
      power_score: 9,
      chapter_idx: 1,
      highlight_words: ["Matrix", "programming", "own mind"],
    },
    {
      text: "I refuse to turn on myself. I'm not going to be the guy who turns on myself and makes an enemy out of my own fucking mind. No sir. Me and every single thing inside of me is on the same team.",
      context: "Reformulation puissante du battle with yourself",
      tags: ["self", "alliance", "psychologie"],
      rhetorical_device: "Anti-cliché stoïcien (refus explicite)",
      power_score: 10,
      chapter_idx: 1,
      highlight_words: ["refuse to turn on myself", "same team"],
    },
    {
      text: "Chasing happiness is probably the most asinine thing you can do. It's the easiest way to lose as a man. What will make me happy is not how you win as a man. How you win as a man is I don't care how I feel — what must be done.",
      context: "Substitution d'axe majeure",
      tags: ["bonheur", "substitution", "axe"],
      rhetorical_device: "Substitution d'axe (happy/sad → duty/abandon)",
      power_score: 10,
      chapter_idx: 2,
      highlight_words: ["chasing happiness", "asinine", "what must be done"],
    },
    {
      text: "As a man, you can't say, 'I will perform when I feel good.' It doesn't work that way cuz our heads are too complicated and life's too complicated.",
      context: "Impossibilité de la performance conditionnelle à l'humeur",
      tags: ["performance", "humeur", "impossible"],
      rhetorical_device: "Négation + justification par la complexité",
      power_score: 7,
      chapter_idx: 2,
      highlight_words: ["can't say", "feel good"],
    },
    {
      text: "Your love as a man is directly correlated to your competence and your capabilities. So when a man who is capable loves you, it means something. A man who's incapable loves you, it means nothing at all.",
      context: "Argument déstabilisant sur la valeur de l'amour",
      tags: ["amour", "competence", "valeur"],
      rhetorical_device: "Conditionnement d'un absolu (amour) à une métrique froide",
      power_score: 8,
      chapter_idx: 3,
      highlight_words: ["directly correlated", "means something", "means nothing"],
    },
    {
      text: "If you have a woman who you truly love, instead of buying her flowers every day, you should improve yourself.",
      context: "Prescription pratique à partir de l'argument précédent",
      tags: ["amour", "prescription", "self-improvement"],
      rhetorical_device: "Contraste geste symbolique vs geste structurel",
      power_score: 8,
      chapter_idx: 3,
      highlight_words: ["improve yourself", "flowers"],
    },
    {
      text: "It's a video game. I want a high score.",
      context: "La vie réduite à un RPG explicite",
      tags: ["video-game", "metaphore", "ego"],
      rhetorical_device: "Métaphore vidéoludique + assumer l'ego",
      power_score: 9,
      chapter_idx: 4,
      highlight_words: ["video game", "high score"],
    },
    {
      text: "This game is extremely difficult. My best chance is to level up my character to a point where the game becomes easy.",
      context: "Stratégie du RPG appliquée à la vie",
      tags: ["strategie", "level-up", "video-game"],
      rhetorical_device: "Extension de la métaphore vidéoludique",
      power_score: 9,
      chapter_idx: 4,
      highlight_words: ["level up", "game becomes easy"],
    },
    {
      text: "Name a time in history that was better to be a man. Was it better to be a man in World War II? Was it better to be a man on the Titanic? Was it better to be a man the Napoleonic Wars? Was it better to be a man when you were sitting in Vienna and the Mongol horde arrived? Building the pyramids. Was that fun? It's always sucked.",
      context: "Argument historique par questions empilées",
      tags: ["histoire", "questions-rhetoriques", "condition-masculine"],
      rhetorical_device: "Questions rhétoriques empilées + réponse implicite",
      power_score: 10,
      chapter_idx: 5,
      highlight_words: ["Name a time", "always sucked"],
    },
    {
      text: "Everyone accepts that the best possible human experience that exists is the top 2% of men. Anything below that sucks. As a man, you're better off being a chick.",
      context: "Pyramide masculine + provocation misogyne",
      tags: ["2-percent", "pyramide", "provocation"],
      rhetorical_device: "Fausse précision (2%) + provocation",
      power_score: 6,
      chapter_idx: 5,
      highlight_words: ["top 2% of men", "better off being a chick"],
    },
    {
      text: "Your happiness as a man comes from feeling respected over feeling loved.",
      context: "Substitution respect/amour",
      tags: ["respect", "amour", "hierarchie"],
      rhetorical_device: "Substitution hiérarchique",
      power_score: 8,
      chapter_idx: 6,
      highlight_words: ["respected over", "loved"],
    },
    {
      text: "Male depression can be fixed with respect.",
      context: "Thèse psychologique forte",
      tags: ["depression", "respect", "thèse"],
      rhetorical_device: "Assertion aphoristique",
      power_score: 9,
      chapter_idx: 6,
      highlight_words: ["male depression", "fixed with respect"],
    },
    {
      text: "If you get in your car and you start driving and you slide a little bit, you're going to keep driving like a fucking idiot until you crash properly. That's how it goes. That's man.",
      context: "Métaphore mécanique de l'orgueil masculin",
      tags: ["orgueil", "metaphore", "apprentissage"],
      rhetorical_device: "Métaphore mécanique (voiture qui dérape)",
      power_score: 8,
      chapter_idx: 6,
      highlight_words: ["slide a little", "crash properly"],
    },
    {
      text: "Every single thing about me that people respect, I built. I was not born a world champion kickboxer. I was not born this intelligent. I was not born this rich. I was not born this strong. I was not born this confident. I was not born none of these things. I became these things myself. So, I deserve all the spoils of war.",
      context: "Anaphore en sept temps",
      tags: ["auto-construction", "anaphore", "spoils"],
      rhetorical_device: "Anaphore septuple 'I was not born'",
      power_score: 10,
      chapter_idx: 4,
      highlight_words: ["I built", "was not born", "spoils of war"],
    },
    {
      text: "I believe men have the sacred duty to protect and provide for the important people in their lives.",
      context: "Ouverture du credo",
      tags: ["credo", "sacred-duty", "protection"],
      rhetorical_device: "Litanie liturgique",
      power_score: 8,
      chapter_idx: 7,
      highlight_words: ["I believe", "sacred duty", "protect", "provide"],
    },
    {
      text: "I believe that a man has the sacred duty to hold true to his word and do exactly what he says he will do.",
      context: "Article du credo — parole donnée",
      tags: ["credo", "parole", "honneur"],
      rhetorical_device: "Répétition anaphorique (I believe)",
      power_score: 9,
      chapter_idx: 7,
      highlight_words: ["hold true to his word"],
    },
    {
      text: "I believe I have an imperative to only spend my time in a way that I determine is beneficial, uplifting, and empowering to myself and others.",
      context: "Article du credo — temps",
      tags: ["credo", "temps", "utilite"],
      rhetorical_device: "Anaphore + tricolon (beneficial/uplifting/empowering)",
      power_score: 8,
      chapter_idx: 7,
      highlight_words: ["only spend my time", "beneficial", "uplifting", "empowering"],
    },
    {
      text: "If I believe the sky is green, but it doubles my net worth. I mean, is that true? My net worth is doubled because of it. So what is truth? True and false is adopting the mindset or the strategies which allow you to compete and win. That's what's true.",
      context: "Pragmatisme épistémique extrême",
      tags: ["verite", "pragmatisme", "sophisme"],
      rhetorical_device: "Pragmatisme épistémique + auto-justification",
      power_score: 10,
      chapter_idx: 8,
      highlight_words: ["sky is green", "doubles my net worth", "what is truth"],
    },
    {
      text: "We can no longer walk the earth and conquer land. So now we conquer the land financially.",
      context: "Substitution historique de la conquête",
      tags: ["conquete", "argent", "sublimation"],
      rhetorical_device: "Substitution historique",
      power_score: 8,
      chapter_idx: 8,
      highlight_words: ["conquer land", "conquer the land financially"],
    },
    {
      text: "Men have that innate desire for conquest. So that's the second best thing I guess is to get rich.",
      context: "Argent comme sublimation de la conquête",
      tags: ["conquete", "argent", "anthropologie"],
      rhetorical_device: "Ordre hiérarchique (second best)",
      power_score: 7,
      chapter_idx: 8,
      highlight_words: ["innate desire", "get rich"],
    },
    {
      text: "How's a woman going to respect you as a man if you're putting her above all your boys? How's a woman going to respect you as a man if you don't respect yourself or other men don't respect you? Respect is linked to fear.",
      context: "Questions empilées sur le respect masculin",
      tags: ["respect", "questions", "peur"],
      rhetorical_device: "Questions rhétoriques empilées + conclusion",
      power_score: 7,
      chapter_idx: 6,
      highlight_words: ["respect", "linked to fear"],
    },
    {
      text: "I'm glad God put me in jail. That's the mental model I've decided because I refuse to believe in anything that takes power away from me.",
      context: "Application radicale du reframe",
      tags: ["reframe", "jail", "pouvoir"],
      rhetorical_device: "Reframe autobiographique + auto-justification",
      power_score: 9,
      chapter_idx: 4,
      highlight_words: ["glad God put me in jail", "refuse to believe"],
    },
    {
      text: "If you're waking up and going, am I happy? Am I not? You're looking at life wrong. Move happiness down the scale. Look at: Am I successful? Am I competent? Am I respected?",
      context: "Reformulation des vrais indicateurs",
      tags: ["indicateurs", "prescription", "substitution"],
      rhetorical_device: "Questions substituées",
      power_score: 8,
      chapter_idx: 2,
      highlight_words: ["move happiness down", "successful", "competent", "respected"],
    },
  ],

  argumentation_kit: {
    how_to_defend: [
      {
        challenge: "Si on te dit : 'La dichotomie Matrice/self-fight est fausse — beaucoup vivent en dehors'",
        response: "Reconnaître la fausse dichotomie apparente + garder la valeur de la métaphore comme réveil",
        technique: "Concession logique + fonction rhétorique",
        example_response_text: "Formellement tu as raison — beaucoup vivent dans un entre-deux confortable. Mais Tate n'écrit pas un traité de sociologie, il donne un choc de conscience. La question utile qui reste : sur mes 168h/semaine, combien vraiment sont vécues, combien sont subies ? La dichotomie force cette question — c'est sa fonction.",
      },
      {
        challenge: "Si on te dit : 'Male depression fixable by respect est de la minimisation clinique'",
        response: "Distinguer dépression clinique (biologique, multifactorielle) et perte de sens masculine (statutaire, existentielle)",
        technique: "Distinction diagnostique",
        example_response_text: "Pour la MDD (major depressive disorder), la prescription 'get respect' est dangereuse et minimisante. Pour la crise de sens masculin (perte de statut, perte de rôle, isolation) — que beaucoup de jeunes hommes vivent — la reconquête d'une compétence respectée est effectivement thérapeutique. Tate confond les deux, mais son point tient pour le second cas.",
      },
      {
        challenge: "Si on te dit : 'Ton amour = ta compétence est faux — un père pauvre peut aimer son enfant'",
        response: "Distinguer amour éprouvé (subjectif) et amour utile (opérationnel)",
        technique: "Distinction subjectif/opérationnel",
        example_response_text: "L'amour éprouvé — celui du père qui pleure sur son enfant — est toujours réel, quelle que soit la compétence. Mais l'amour opérationnel — celui qui protège, nourrit, éduque, ouvre des portes — dépend effectivement de la capacité. Tate ne dit pas 'le pauvre père n'aime pas', il dit 'son amour ne peut pas produire les mêmes effets'. Distinction utile même si formulée trop dure.",
      },
      {
        challenge: "Si on te dit : 'La litanie I believe est de la manipulation liturgique'",
        response: "Reconnaître l'effet + isoler les articles individuellement défendables",
        technique: "Décomposition ligne à ligne",
        example_response_text: "L'effet cumulé est effectivement liturgique — l'anaphore massive court-circuite la critique article par article. C'est une technique. Mais pris individuellement, beaucoup d'articles sont défendables (tenir parole, protéger ses enfants, entraîner son corps). D'autres sont discutables (raise strong sons — implique-t-on que les filles ne comptent pas ?). Il faut décomposer.",
      },
    ],
    how_to_attack: [
      {
        target_claim: "If I believe the sky is green but it doubles my net worth — that's true.",
        attack: "Sophisme assumé qui autorise le mensonge quand il paie. Position philosophiquement intenable (auto-réfutante : si la vérité c'est ce qui paie, alors dire que 'la vérité c'est ce qui paie' n'est vrai que si ça paie — régression). Éthiquement, c'est la définition du cynisme.",
        angle: "Logique + Éthique",
      },
      {
        target_claim: "Top 2% of men live good — anything below sucks.",
        attack: "Statistique inventée sans source. Faux empiriquement : les études sur life satisfaction masculine (Blanchflower & Oswald, Kahneman) montrent une distribution continue, pas un cliff à 98%. Utilisé pour vendre l'espoir d'atteindre le 2%.",
        angle: "Empirique",
      },
      {
        target_claim: "Male depression can be fixed with respect.",
        attack: "Minimisation clinique. Le MDD a des causes biologiques (héritabilité 40%), sociales et cognitives — le respect n'est qu'un des facteurs, pas 'le' facteur. Prescrire du respect à un dépressif clinique retarde le traitement médicamenteux/thérapeutique nécessaire.",
        angle: "Empirique",
      },
      {
        target_claim: "As a man, you're better off being a chick.",
        attack: "Ignore les statistiques de violences (femicides, violences domestiques), l'écart salarial, la charge mentale et les biais médicaux (sous-diagnostic féminin en cardiologie). Réifie la condition féminine comme confort — factuellement faux.",
        angle: "Éthique + Empirique",
      },
    ],
    how_to_rephrase: [
      {
        original: "Chasing happiness is the most asinine thing you can do.",
        softer: "Faire du bonheur ressenti la variable centrale de sa vie mène souvent à des décisions court-terme regrettables.",
        harder: "Chercher le bonheur, c'est la façon la plus rapide de perdre. Cherche ce qui doit être fait.",
        academic: "L'orientation eudémonique (recherche de sens et d'accomplissement) prédit mieux le bien-être long terme que l'orientation hédonique (recherche de plaisir immédiat) — cf. Ryan & Deci.",
      },
      {
        original: "Your love as a man is directly correlated to your competence.",
        softer: "L'amour d'un homme prend une valeur opérationnelle proportionnelle à sa capacité de le traduire en actes protecteurs et pourvoyeurs.",
        harder: "Ton amour vaut ce que tu peux faire. Un père qui ne peut pas nourrir, ne peut pas aimer utilement.",
        academic: "L'amour comme lien affectif est indépendant de la capacité — mais l'amour comme fonction protectrice et pourvoyeuse (theorie de l'attachement + Bowlby) requiert une compétence opérationnelle mesurable.",
      },
      {
        original: "Male depression can be fixed with respect.",
        softer: "La reconnaissance sociale et la sensation d'importance sont des facteurs protecteurs majeurs contre certaines formes de mal-être masculin.",
        harder: "Le respect guérit la dépression masculine. Reconstruis ton statut, tu retrouveras ta forme.",
        academic: "La perte de statut social masculin (Kilmartin, Real) est un facteur causal identifié dans les crises psychologiques masculines contemporaines — sans épuiser les causes de la MDD.",
      },
      {
        original: "It's a video game. I want a high score.",
        softer: "Traiter la vie comme un système à progression permet de rester dans une posture d'agentivité constante.",
        harder: "C'est un jeu. Je veux gagner. Fin.",
        academic: "La gamification cognitive de l'existence (Kotler, McGonigal) transforme la charge motivationnelle en dynamique de progression mesurable — impact documenté sur l'engagement.",
      },
      {
        original: "Truth is what allows you to compete and win.",
        softer: "Pour un compétiteur, la valeur opérationnelle d'une croyance peut peser plus lourd que sa vérité factuelle.",
        harder: "La vérité, c'est ce qui gagne. Le reste, c'est du décor.",
        academic: "Le pragmatisme épistémique dans sa version radicale (Rorty) ouvre la voie à un relativisme de la vérité difficilement tenable — la version modérée (James, Dewey) parle d'utilité comme critère parmi d'autres, pas comme définition.",
      },
    ],
    if_asked: [
      {
        question: "Faut-il vraiment abandonner la mesure du bonheur ?",
        best_response: "Non — la substituer par 'duty' est excessif. Mais faire du bonheur ressenti la variable primaire de ses décisions produit des choix court-termistes (l'humeur du jour dicte l'action). Le compromis raisonnable : le bonheur reste une variable, mais elle est ré-hiérarchisée derrière sens, compétence, contribution. Les études sur eudaimonic well-being (Ryan & Deci) confirment ce classement.",
        followup_moves: [
          "Distinguer bonheur ressenti court-terme vs bonheur eudémonique long-terme",
          "Rappeler que Tate confond les deux dans son attaque",
        ],
      },
      {
        question: "L'idée 'ton amour = ta compétence' est-elle défendable ?",
        best_response: "En partie. L'amour éprouvé (le lien affectif) est indépendant de la compétence — un père en prison peut aimer son enfant profondément. Mais l'amour opérationnel (la capacité à protéger, éduquer, transmettre) dépend effectivement de ce qu'on est capable de faire. La formule de Tate est dure mais elle pointe une vérité : dire 'je t'aime' sans pouvoir agir sur cet amour est plus faible que 'je t'aime' + capacité.",
        followup_moves: [
          "Illustrer avec la théorie de l'attachement (Bowlby)",
          "Souligner : la compétence sans amour est aussi vide que l'amour sans compétence",
        ],
      },
      {
        question: "Le credo I believe est-il un manifeste défendable ou un endoctrinement ?",
        best_response: "Ni l'un ni l'autre en bloc — il faut le décomposer. Certains articles sont défendables (tenir parole, entraîner son corps, protéger sa famille, poursuivre l'excellence). D'autres sont discutables (raise strong sons — pas de mention des filles) ou méritent nuance (ne parler qu'à ceux qui te respectent — peut virer chambre d'écho). L'effet cumulé est liturgique et court-circuite l'examen critique — c'est la vraie technique à connaître.",
        followup_moves: [
          "Proposer de sélectionner 7 articles pour son propre credo",
          "Attention à l'effet chambre d'écho de 'only interact with those who respect me'",
        ],
      },
      {
        question: "Que penser de 'truth is what allows you to win' ?",
        best_response: "Philosophiquement intenable et éthiquement dangereux. Auto-réfutant : si la vérité c'est ce qui paie, la phrase 'la vérité c'est ce qui paie' n'est vraie que si elle paie — régression infinie. Pratiquement : autorise le mensonge à soi-même et aux autres. C'est le sophisme le plus assumé de Tate — cas d'école à savoir démonter. Utile pour Auguste : reconnaître ce mouvement chez ses interlocuteurs et le nommer.",
        followup_moves: [
          "Nommer le mouvement : pragmatisme épistémique radical",
          "Réponse standard : 'ce qui marche' n'est pas 'ce qui est vrai' — les deux peuvent coïncider ou pas",
        ],
      },
      {
        question: "Comment appliquer 'life is a video game' concrètement ?",
        best_response: "Trois principes opérationnels : (1) identifier ses 5-6 stats clefs (force physique, connaissances, réseau, capital, communication, santé) et les scorer sur 100 tous les 3 mois, (2) traiter les objectifs comme des quêtes avec des critères objectifs de complétion, (3) accepter les 'boss fights' (obstacles difficiles) comme des paliers nécessaires plutôt que des injustices. Utile sans souscrire à toute la doctrine.",
        followup_moves: [
          "Créer une character sheet personnelle et la revoir trimestriellement",
          "Piège : la gamification excessive peut réduire l'authenticité — doser",
        ],
      },
      {
        question: "L'argument 'name a time better to be a man' tient-il ?",
        best_response: "Rhétoriquement très puissant, factuellement discutable. Presque toutes les métriques objectives (espérance de vie, mortalité maternelle, accès à l'éducation, sécurité physique) montrent que le XXIe siècle est le meilleur moment de l'histoire pour être un homme. L'argument de Tate joue sur la nostalgie d'un rôle héroïque perdu, pas sur la condition matérielle. Il faut distinguer : condition matérielle (jamais meilleure) vs rôle symbolique masculin (en crise identitaire).",
        followup_moves: [
          "Citer les stats WHO/UN sur espérance de vie masculine",
          "Reconnaître la crise du rôle sans confondre avec la crise de condition",
        ],
      },
    ],
  },

  fallacies: [
    {
      original_claim: "You either fight the matrix or fight yourself — you can't escape this fight.",
      fallacy_type: "false dichotomy",
      why_fallacious: "Réduit à deux options une situation qui en offre beaucoup plus (contribuer localement, s'adapter, se retirer, jouer sans être en guerre). Le cadre binaire sert à polariser, pas à décrire.",
      steelman: "Comme choc de conscience, la formule oblige à sortir de la passivité et à prendre position — sa fonction est rhétorique, pas descriptive.",
      nuance: "Vrai comme injonction à ne pas subir sans conscience. Faux comme description exhaustive des options disponibles.",
      counter_argument: "Un artisan qui fait bien son métier, aime sa famille, contribue à sa communauté n'est ni en guerre contre la Matrice ni contre lui-même. Il est simplement présent. La dichotomie de Tate rate cette vaste catégorie.",
      severity: "medium",
    },
    {
      original_claim: "Chasing happiness is the most asinine thing you can do.",
      fallacy_type: "straw man + hyperbole",
      why_fallacious: "Attaque une version caricaturale du 'chase happiness' (drogues, hédonisme court-terme) comme si c'était la seule. La psychologie positive contemporaine (Seligman, PERMA) distingue plusieurs types de bien-être — plusieurs sont compatibles avec la discipline masculine.",
      steelman: "Le point utile : faire du ressenti immédiat la variable de décision produit des choix court-termistes. Tate attaque un vrai problème sous une forme excessive.",
      nuance: "Vrai contre l'hédonisme comme mode de vie. Faux comme rejet du bien-être eudémonique — qui est en réalité aligné avec la thèse de Tate sur la discipline et la contribution.",
      counter_argument: "Seligman (PERMA), Ryan & Deci (SDT) : les gens qui poursuivent le sens, l'accomplissement et la contribution rapportent une satisfaction supérieure à ceux qui poursuivent le plaisir. Le 'chase happiness' bien compris est exactement ce que Tate prescrit — sans se rendre compte.",
      severity: "medium",
    },
    {
      original_claim: "Your love as a man is directly correlated to your competence.",
      fallacy_type: "confusion catégorielle",
      why_fallacious: "Confond deux registres : l'amour comme lien affectif (indépendant de la compétence) et l'amour comme capacité protectrice (dépendant de la compétence). Tate fusionne les deux et conclut que le lien affectif est nul si la compétence est faible.",
      steelman: "La partie utile : la capacité à AGIR sur son amour (nourrir, protéger, ouvrir des portes) dépend de la compétence. Sans cela, l'amour reste intention pure.",
      nuance: "L'amour éprouvé et l'amour opérationnel sont deux dimensions distinctes — Tate n'en garde qu'une. Il faut les deux : lien affectif + capacité d'action.",
      counter_argument: "Théorie de l'attachement (Bowlby, Ainsworth) : un enfant a besoin d'un lien affectif sécurisé pour se développer psychologiquement, indépendamment du niveau matériel. Un parent aimant pauvre produit de meilleurs enfants qu'un parent absent riche.",
      severity: "high",
    },
    {
      original_claim: "Top 2% of men live good. Anything below sucks. As a man you're better off being a chick.",
      fallacy_type: "statistique inventée + faux dilemme + misogynie",
      why_fallacious: "Le '2%' n'a aucune source. La distribution du bien-être masculin est continue, pas à seuil. La comparaison 'better off being a chick' ignore les données objectives sur les inégalités subies par les femmes.",
      steelman: "La pyramide de statut masculin est réelle — la variance de bien-être masculin est significative selon la position statutaire (Baumeister). L'idée qu'il y a un top et un bas est correcte, le chiffre est inventé.",
      nuance: "Vrai : les hommes au bas du statut masculin ont des marqueurs de mal-être élevés. Faux : cela ne signifie ni que le bas est 98% ni que la condition féminine est meilleure.",
      counter_argument: "Blanchflower & Oswald sur le U-shape du bien-être : la distribution est continue avec un creux à 45-50 ans pour tous les sexes. La condition féminine reste marquée par des marqueurs objectifs de désavantage (violence, écart salarial, biais médicaux).",
      severity: "high",
    },
    {
      original_claim: "Male depression can be fixed with respect.",
      fallacy_type: "minimisation clinique",
      why_fallacious: "Le trouble dépressif majeur (MDD) a une héritabilité de 40%, des marqueurs neuroendocriniens et cognitifs. La prescription 'get respect' pour un dépressif clinique est aussi absurde que 'get respect' pour un diabétique.",
      steelman: "Pour les états de démoralisation masculine liés à la perte de statut, la reconquête d'une compétence respectée EST effectivement thérapeutique (behavioral activation + reconstruction identitaire).",
      nuance: "La formule est utile pour la crise de sens masculin, dangereuse pour la MDD. Tate confond les deux — dommage réel car son audience jeune peut retarder un vrai traitement.",
      counter_argument: "OMS 2023 : 280 millions de personnes en dépression clinique. Le mécanisme n'est pas la carence de respect. Les traitements efficaces sont thérapie + parfois médicaments + exercice physique. Le respect vient après, pas à la place.",
      severity: "high",
    },
    {
      original_claim: "Truth is what allows you to compete and win.",
      fallacy_type: "pragmatisme radical + auto-réfutation",
      why_fallacious: "Auto-réfutant : si la vérité c'est ce qui paie, alors 'la vérité c'est ce qui paie' n'est vrai que si ça paie — régression. Éthiquement, autorise le mensonge intéressé comme mode normal.",
      steelman: "La version modérée du pragmatisme (James, Dewey) — l'utilité est un critère parmi d'autres pour évaluer une croyance — est philosophiquement défendable. Tate en prend la version radicale et intenable.",
      nuance: "Vrai que certaines croyances motivationnelles utiles sont techniquement fausses (l'entraînement va marcher, je vais réussir). Faux qu'on peut en tirer une théorie générale de la vérité.",
      counter_argument: "Si toute vérité est ce qui gagne, alors les nazis avaient 'raison' quand ils gagnaient — insoutenable. Le critère 'ce qui marche' ne peut pas remplacer la correspondance avec la réalité. Cette phrase de Tate est la définition même du cynisme.",
      severity: "high",
    },
    {
      original_claim: "Name a time in history that was better to be a man. It's always sucked.",
      fallacy_type: "cherry-picking historique + nostalgie inversée",
      why_fallacious: "Sélectionne uniquement les moments dramatiques (WW2, Titanic, Mongols) et ignore les périodes de paix relative + la trajectoire d'amélioration continue depuis 200 ans. Toutes les métriques objectives (espérance de vie, mortalité, éducation, sécurité) sont favorables au XXIe siècle.",
      steelman: "Ce que Tate pointe : le rôle symbolique masculin (guerrier, pourvoyeur exclusif, protecteur physique) est effectivement en crise identitaire — beaucoup d'hommes cherchent une fonction. La crise de rôle est réelle.",
      nuance: "Distinguer condition matérielle (jamais meilleure) et rôle symbolique (en crise). Tate confond les deux pour amplifier son propos.",
      counter_argument: "Espérance de vie masculine en 1900 = 46 ans, en 2024 = 79 ans dans les pays développés. Mortalité au travail divisée par 20. Accès universel à l'éducation. Le XXIe siècle est objectivement le meilleur moment d'être un homme. Le rôle a changé, la condition s'est améliorée.",
      severity: "medium",
    },
    {
      original_claim: "As a man, life is war. You should try and be the best possible version of yourself in all realms.",
      fallacy_type: "hyperbole métaphorique + généralisation",
      why_fallacious: "La métaphore de la guerre est utile pour mobiliser mais elle érige la compétition en principe existentiel unique. Ignore la coopération, l'amitié, la contemplation, l'art — dimensions de la vie masculine tout aussi documentées historiquement.",
      steelman: "Comme correctif face à une culture qui a effacé toute compétition masculine, la métaphore fonctionne comme rééquilibrage. La compétition est un besoin réel.",
      nuance: "Vrai que la compétition est une dimension masculine négligée dans la culture contemporaine. Faux que c'est LA dimension exclusive. Aristote, Sénèque, Montaigne ont écrit des vies masculines réussies sans jamais parler de 'war'.",
      counter_argument: "Les Blue Zones (Sardaigne, Okinawa) — populations avec la plus grande longévité masculine — sont caractérisées par coopération, communauté, jeu partagé. La compétition permanente est associée au cortisol chronique et à la mortalité cardiaque précoce.",
      severity: "medium",
    },
  ],

  stats: [
    {
      number: "2%",
      label: "des hommes qui auraient une 'bonne vie' selon Tate (chiffre inventé)",
      source: "Tate — vidéo",
      context: "Base pyramidale de son argument — statistique non-sourcée",
      visual: "percent",
    },
    {
      number: "20+",
      label: "articles de foi 'I believe' dans le credo final (litanie des sacred duties)",
      source: "Tate — vidéo",
      context: "Volume qui crée l'effet liturgique cumulé",
      visual: "count-up",
    },
    {
      number: "110",
      label: "personnes qui dépendent du wage de Tate selon son propre chiffrage",
      source: "Tate — '110 people rely on me for a wage'",
      context: "Utilisé pour illustrer son 'giving' de patron",
      visual: "count-up",
    },
    {
      number: "3",
      label: "problèmes de la vie de Tate avant richesse ultime (santé, femme, argent)",
      source: "Tate — vidéo",
      context: "Réduction opérationnelle des problèmes de vie",
      visual: "count-up",
    },
    {
      number: "5",
      label: "questions rhétoriques empilées sur 'when was it better to be a man'",
      source: "Tate — WW2, Titanic, Napoleon, Vienne/Mongols, pyramides",
      context: "Structure rhétorique — questions empilées",
      visual: "count-up",
    },
  ],

  comparisons: [
    {
      title: "Deux choix selon Tate",
      left: {
        label: "Fight the Matrix",
        items: [
          "Se réveiller au vrai",
          "Bâtir sa richesse contre le système",
          "S'entraîner physiquement",
          "Ennemi extérieur clair",
        ],
      },
      right: {
        label: "Fight yourself",
        items: [
          "Accepter le programme",
          "Semi-dépression rampante",
          "Sitting on internet",
          "Ennemi intérieur (self)",
        ],
      },
    },
    {
      title: "Happy/sad vs Duty/abandon",
      left: {
        label: "Axe happy/sad (à abandonner)",
        items: [
          "Am I happy today?",
          "Dépend de l'humeur",
          "Court-termiste",
          "Mène à l'hédonisme temporaire",
        ],
      },
      right: {
        label: "Axe duty/abandon (à adopter)",
        items: [
          "What must be done?",
          "Indépendant de l'humeur",
          "Long-termiste",
          "Mène à la fierté & au respect",
        ],
      },
    },
    {
      title: "Amour d'un capable / Amour d'un incapable",
      left: {
        label: "Amour du capable",
        items: [
          "Peut nourrir + protéger",
          "Peut ouvrir des portes",
          "Actes qui matchent les mots",
          "'It means something'",
        ],
      },
      right: {
        label: "Amour de l'incapable",
        items: [
          "Ne peut ni nourrir ni protéger",
          "Aucune porte à ouvrir",
          "Mots sans actes",
          "'It means nothing at all'",
        ],
      },
    },
    {
      title: "Respect vs Amour dans la hiérarchie masculine",
      left: {
        label: "Respect (Tate priorise)",
        items: [
          "Vient du statut construit",
          "Guérirait la dépression masculine",
          "Se cumule avec la peur",
          "Précède la femme aimante",
        ],
      },
      right: {
        label: "Amour (Tate déprioriseent)",
        items: [
          "Vient sans être mérité",
          "Ne guérirait pas seul",
          "Peut coexister avec le mépris",
          "Sans respect, l'amour se retire",
        ],
      },
    },
  ],

  devices: [
    {
      name: "Anaphore quintuple (in this fight)",
      example_text: "Everybody watching this is in this fight. I'm in this fight. You're in this fight. We're all in this fight. The war is here.",
      effect: "Crée un effet d'enveloppement — dissout toute possibilité d'extériorité",
      why_it_works: "La répétition en cinq temps supprime toute échappatoire cognitive — l'auditeur ne peut plus se penser hors du cadre",
    },
    {
      name: "Questions rhétoriques empilées",
      example_text: "Was it better to be a man in World War II? Was it better to be a man on the Titanic? Was it better to be a man the Napoleonic Wars?",
      effect: "Force l'auditeur à reconnaître l'absence de réponse — donc la validité du propos",
      why_it_works: "Chaque question ferme une porte — au bout de 4-5, l'auditeur n'a plus de contre-exemple à opposer",
    },
    {
      name: "Litanie performative (I believe)",
      example_text: "I believe men have the sacred duty to protect and provide. I believe men have the sacred duty to protect the innocence of their children...",
      effect: "Imite la prière liturgique — crée un effet de credo, de serment partagé",
      why_it_works: "La forme religieuse court-circuite l'examen critique article par article — l'effet cumulé prend le pas",
    },
    {
      name: "Substitution d'axe conceptuel",
      example_text: "How happy you are is a pointless measurement. What must be done — that's the axis.",
      effect: "Reformule le débat en imposant son cadre conceptuel",
      why_it_works: "L'auditeur ne débat plus sur happy/sad — il débat sur duty/abandon, terrain que Tate a choisi",
    },
    {
      name: "Fausse précision statistique",
      example_text: "Top 2% of men live good. Anything below sucks.",
      effect: "Crée une fausse précision qui se grave en mémoire",
      why_it_works: "Le chiffre '2%' semble plus autoritaire que 'la plupart des hommes' — même s'il est inventé, il structure la pensée",
    },
    {
      name: "Métaphore mécanique (voiture qui dérape)",
      example_text: "You get in your car and you slide a little bit, you're going to keep driving like a fucking idiot until you crash properly.",
      effect: "Rend visible un concept abstrait (l'orgueil masculin obstiné)",
      why_it_works: "L'image cinétique active la mémoire motrice — l'auditeur 'voit' le crash inévitable",
    },
    {
      name: "Anaphore septuple (I was not born)",
      example_text: "I was not born a world champion kickboxer. I was not born this intelligent. I was not born this rich...",
      effect: "Sept négations construisant un crescendo qui débouche sur l'affirmation 'I deserve'",
      why_it_works: "L'auditeur sent la construction cumulative — chaque 'I was not born' rend le 'I built' final imparable",
    },
    {
      name: "Pragmatisme épistémique",
      example_text: "What is truth? True and false is adopting the mindset which allows you to compete and win.",
      effect: "Court-circuite la vérité par l'efficacité — provoque autant qu'il convainc",
      why_it_works: "L'auditeur reste en suspension — la thèse est intellectuellement scandaleuse mais opérationnellement claire",
    },
    {
      name: "Métaphore vidéoludique",
      example_text: "It's a video game. I want a high score. Level up your character to a point where the game becomes easy.",
      effect: "Transforme l'existence en système à progression — rend la vie manipulable",
      why_it_works: "La génération gamer reconnaît immédiatement les mécaniques — la métaphore économise 30 minutes d'explication",
    },
    {
      name: "Dichotomie forcée",
      example_text: "You either wake up and battle the Matrix or you accept the programming.",
      effect: "Réduit à deux options une situation complexe — force le choix",
      why_it_works: "La contrainte binaire empêche le confortable 'oui mais' — l'auditeur doit prendre position",
    },
  ],

  analogies: [
    {
      source: "Video game — level up + high score",
      used_for: "Rendre la vie tangible et progressable",
      strength: 9,
      why_it_works: "Génération familière du RPG — mécaniques de leveling immédiatement compréhensibles",
    },
    {
      source: "Voiture qui dérape jusqu'au crash",
      used_for: "Illustrer l'obstination masculine face aux signaux d'avertissement",
      strength: 8,
      why_it_works: "Image cinétique + expérience commune (chacun a déjà entendu un pneu déraper)",
    },
    {
      source: "Ferrari vs push bike sur circuit",
      used_for: "L'inégalité entre l'homme préparé et l'homme non préparé face aux femmes",
      strength: 8,
      why_it_works: "Contraste visuel immédiat + impossibilité manifeste de rattraper",
    },
    {
      source: "Matrix (film)",
      used_for: "Nommer le système de programmation contre lequel Tate se dresse",
      strength: 7,
      why_it_works: "Référence culturelle universelle — court-circuite la définition d'un système d'oppression",
    },
    {
      source: "Roman qui traverse la terre pour la conquérir",
      used_for: "Sublimation de la conquête militaire en conquête financière",
      strength: 7,
      why_it_works: "L'imaginaire romain donne un poids historique à un désir contemporain (être CEO)",
    },
    {
      source: "Mongol horde arrivant à Vienne",
      used_for: "Illustrer qu'aucune époque n'a été confortable pour être un homme",
      strength: 8,
      why_it_works: "Image extrême, spécifique et vérifiable — crée le contraste maximal avec le confort moderne",
    },
  ],

  frameworks: [
    {
      name: "Substitution d'axe (happy/sad → duty/abandon)",
      when_to_use: "Quand on se surprend à évaluer ses décisions par 'est-ce que je serai plus heureux ?'",
      steps: [
        "Étape 1 : reconnaître la question qui vient (am I happy?)",
        "Étape 2 : la remplacer par 'what must be done?'",
        "Étape 3 : identifier UNE action que le duty impose",
        "Étape 4 : exécuter cette action et noter le ressenti a posteriori",
      ],
      warning: "Ne pas devenir sourd à ses émotions — le duty pur produit du burnout. Le bonheur reste une variable de contrôle, pas la variable de décision.",
    },
    {
      name: "Character sheet (approche gamer)",
      when_to_use: "Trimestriel, pour se situer dans son propre RPG de vie",
      steps: [
        "Étape 1 : lister 6 stats clefs (force, connaissances, réseau, capital, communication, santé)",
        "Étape 2 : se noter sur 100 pour chacune (auto-évaluation honnête)",
        "Étape 3 : identifier la stat la plus faible qui bloque les autres",
        "Étape 4 : consacrer le trimestre à faire monter cette stat de 10 points",
      ],
      warning: "Attention à la sur-quantification — certaines dimensions de la vie (amitié, contemplation) ne se stat-ifient pas bien",
    },
    {
      name: "Credo I believe (personnalisé)",
      when_to_use: "Une fois — pour établir ses non-négociables",
      steps: [
        "Étape 1 : écrire 15 'Je crois' bruts sur ses convictions les plus profondes",
        "Étape 2 : garder les 7 qui restent solides après 48h de recul",
        "Étape 3 : les afficher physiquement dans son espace de travail",
        "Étape 4 : les relire chaque lundi matin — modifier après 6 mois si nécessaire",
      ],
      warning: "Ne pas confondre credo et dogme — un vrai credo évolue avec l'expérience",
    },
    {
      name: "Reframe 'glad God put me here' (protocole radical)",
      when_to_use: "Face à un événement subi (échec, jail, séparation) qu'on ne peut pas changer",
      steps: [
        "Étape 1 : accepter le fait — il a eu lieu",
        "Étape 2 : décider en actes de le voir comme formateur ('glad this happened')",
        "Étape 3 : identifier UN apprentissage qu'on n'aurait pas eu sans cela",
        "Étape 4 : agir à partir de cet apprentissage dans les 7 jours",
      ],
      warning: "Ce n'est pas un traitement du trauma — c'est une décision d'orientation. Pour des événements graves, le travail thérapeutique reste nécessaire.",
    },
  ],

  drills: [
    {
      name: "Écrire son I believe personnel",
      duration: "3 sessions de 45 min sur 1 semaine",
      instructions: [
        "Session 1 : écrire 20 'Je crois' bruts sans autocensure",
        "Session 2 : rayer les 8 qui semblent hérités et pas vraiment portés",
        "Session 3 : formuler les 7 gardés en phrases nettes, à voix haute",
        "Afficher et relire chaque lundi matin",
      ],
      difficulty: 3,
    },
    {
      name: "Character sheet trimestrielle",
      duration: "1h tous les 3 mois",
      instructions: [
        "Se noter sur 6 stats : force physique, connaissances, réseau, capital, communication, santé",
        "Comparer à la précédente character sheet",
        "Identifier la stat qui bloque les autres (bottleneck)",
        "Fixer un objectif +10 points sur cette stat pour le trimestre",
      ],
      difficulty: 2,
    },
    {
      name: "Substitution d'axe (7 jours)",
      duration: "7 jours",
      instructions: [
        "À chaque décision de la journée, remarquer la question par défaut ('est-ce que je serai plus heureux ?')",
        "La remplacer par 'what must be done ?'",
        "Noter la décision effectivement prise et la comparer à la décision qu'aurait produit l'ancien axe",
        "Jour 7 : bilan — combien de décisions ont vraiment changé ?",
      ],
      difficulty: 3,
    },
    {
      name: "Questions rhétoriques empilées (rhétorique)",
      duration: "10 jours × 10 minutes",
      instructions: [
        "Chaque jour, prendre une position qu'on veut défendre",
        "Écrire 5 questions rhétoriques qui la soutiennent en obligeant l'adversaire à ne pas trouver de contre-exemple",
        "Répéter à voix haute pour trouver le rythme",
        "Une fois par semaine, tester en conversation réelle",
      ],
      difficulty: 3,
    },
  ],

  related: {
    videos: ["Gv39IoU5Z5s", "AG1vvPVkHC8", "cZwULaBA9Bw"],
    debates: ["masculinite-modernite", "purpose-bonheur"],
  },
};

if (typeof CONTENT_REGISTRY !== 'undefined') CONTENT_REGISTRY["d8FH8K7n0GE"] = CONTENT_d8FH8K7n0GE;
