// /mindmap/content/Gv39IoU5Z5s.js
// Deep content — "Educate Yourself Daily / Hustler's University" — Andrew Tate

const CONTENT_Gv39IoU5Z5s = {
  id: "Gv39IoU5Z5s",
  slug: "educate-yourself-daily",
  title: "Educate Yourself Daily (Hustler's University)",
  speaker: "Andrew Tate",
  format: "cours magistral · manuel business numéroté (points 41-54) + long final discipline",
  word_count: 14600,
  language: "en",

  hook: "Tout dans la vie, c'est des gens qui entrent dans des pièces et qui parlent.",
  thesis: "Le succès se construit par une combinaison froide de compétences observables — parler, vendre, bouger vite, refuser le confort — et le seul discriminant final entre ceux qui réussissent et les autres est la discipline, jamais la motivation.",
  key_takeaways: [
    "Le succès masculin n'est pas dans le job — freedom, network, body language, femmes = les quatre piliers",
    "Speed defies gravity : la vitesse est ton anti-crise universelle",
    "Repeat the question — technique concrète anti-'um' qui te donne du temps de réflexion sans le paraître",
    "Money is water : elle ne se fait pas, elle se prend ; positionne-toi où elle circule",
    "Tell people they can't have things — la rareté fabrique le désir",
    "Discipline > motivation : Tate dit avoir été motivé 25% du temps sur 12 ans",
    "Chaos = opportunity : chaque effondrement contient une monétisation à extraire",
    "Perspicacity + indefatigability = le vrai edge — savoir voir + ne jamais s'arrêter",
  ],

  chapters: [
    {
      idx: 1,
      title: "Redéfinir le succès masculin",
      summary: "Le manager BMW n'est pas un succès. Quatre piliers réels : freedom (temps + géographique), network (qui décroche ton appel), body language / physique (danger perçu), femmes (ultimate status symbol).",
      key_quote: "You ain't a man if you're not free. If you're working your ass off, you're a slave.",
      duration_estimate: "0:00-6:00",
    },
    {
      idx: 2,
      title: "Speaking = selling — tout est parler dans une pièce",
      summary: "Politique, business, cour, congrès — tout est speaking. La technique 'repeat the question' comme anti-hésitation.",
      key_quote: "Everything in life is people walking into rooms and saying things.",
      duration_estimate: "6:00-12:00",
    },
    {
      idx: 3,
      title: "Speed & stress tolerance (règle #1)",
      summary: "Tout va foirer — la seule remédiation est la vitesse. Métaphore du seau qui tourne. Priorité absolue : garder le payment gateway online.",
      key_quote: "Speed defies gravity. If you get water in a bucket and you spin it around really fast, the water doesn't come out.",
      duration_estimate: "12:00-18:00",
    },
    {
      idx: 4,
      title: "Points 41-45 — Recrutement, viser haut, confiance irrationnelle",
      summary: "Hire loyalty first (find work after). Aim way too high (moon/stars/sky gradation). Irrational self-confidence sans être bullshitter — l'exemple du docteur qui doit être confiant.",
      key_quote: "If you aim for the moon, you'll get to the stars. If you aim for the sky, you won't get off the ground.",
      duration_estimate: "18:00-27:00",
    },
    {
      idx: 5,
      title: "Points 46-49 — Money is water, tell people they can't have things",
      summary: "L'argent ne se fait pas, il se prend ('Dan the crackhead' et la métaphore aquatique). La rareté fabrique le désir. Ne pas rendre un employé irremplaçable.",
      key_quote: "Money cannot be made. It can only be taken from someone else.",
      duration_estimate: "27:00-36:00",
    },
    {
      idx: 6,
      title: "Points 50-54 — Chaos, FOMO, war, passion for profit",
      summary: "La plupart des gens connaissent la réponse et ne bougent pas — miss makeup bimbo. Passion for profit, pas pour le produit. War can be profitable si stratégie claire. Chaos = opportunity (aveu de la fausse citation japonaise).",
      key_quote: "I once got told that chaos and opportunity are the same word in Japanese. I don't know if that's true, but I'm going to say it.",
      duration_estimate: "36:00-52:00",
    },
    {
      idx: 7,
      title: "L'ennui chronique — pourquoi Tate fight",
      summary: "Passage introspectif rare : Tate confesse que s'il ne fait rien de difficile, il est en ennui rampant. Le fight comme antidote à la crippling boredom.",
      key_quote: "If I'm not doing something extremely difficult or extremely stressful, I'm in a perpetual state of crippling boredom.",
      duration_estimate: "52:00-58:00",
    },
    {
      idx: 8,
      title: "Discipline > motivation + credo final",
      summary: "12 ans, 5h/jour, 6 jours/semaine — motivé 25% du temps. Motivation is a scam. Want vs want (ice skating). État mental = seule chose contrôlable. Clôture sur 'perspicacity + indefatigability'.",
      key_quote: "Unmatched perspicacity coupled with sheer indefatigability makes me a feared opponent in any realm of human endeavor.",
      duration_estimate: "58:00-fin",
    },
  ],

  argument_tree: {
    root: {
      claim: "Le succès se construit par compétences froides + discipline (pas motivation)",
      children: [
        {
          claim: "Le vrai succès masculin est fait de freedom + network + physique + femmes",
          type: "premise",
          strength: 6,
          evidence: [
            "Le manager BMW n'est un 'success' que dans son immeuble",
            "Female = ultimate status symbol (thèse extrêmement contestable)",
          ],
          children: [
            { claim: "Contre-preuve : de nombreux 'insignifiants publics' vivent des vies pleines et respectées", type: "counter", strength: 8 },
          ],
        },
        {
          claim: "Parler = vendre — tout pouvoir passe par la parole",
          type: "premise",
          strength: 9,
          evidence: [
            "Politique, senate, congress, court, business",
            "'Um' fait perdre la vente — repeat the question",
          ],
          children: [
            { claim: "Cette thèse légitime tout le travail d'Auguste sur l'éloquence", type: "meta", strength: 10 },
          ],
        },
        {
          claim: "Speed défie la gravité — la vitesse est ton edge universel",
          type: "premise",
          strength: 7,
          evidence: [
            "Métaphore du seau",
            "Payment gateway = oxygène",
          ],
          children: [
            { claim: "Nuance : la précipitation crée des erreurs coûteuses — Amazon/Apple gagnent aussi par lenteur stratégique", type: "counter", strength: 7 },
          ],
        },
        {
          claim: "Money is water — elle ne se fait pas, elle se prend",
          type: "analogy",
          strength: 7,
          evidence: [
            "La citation de 'Dan the crackhead' (autorité mystifiée)",
            "99% des business sont des middlemen",
          ],
          children: [
            { claim: "Faux pour l'innovation vraie (médicament, logiciel) — crée de la valeur nouvelle", type: "counter", strength: 8 },
          ],
        },
        {
          claim: "La discipline est réelle, la motivation est un scam",
          type: "premise",
          strength: 8,
          evidence: [
            "25% du temps motivé sur 12 ans",
            "Want ice skate vs want ice skate — deux niveaux de désir",
          ],
          children: [
            { claim: "Nuance neuroscientifique : discipline et motivation se nourrissent mutuellement, pas opposées", type: "counter", strength: 8 },
            { claim: "Aveu : la discipline de Tate est en réalité une fuite de l'ennui chronique — pas du courage", type: "self-reveal", strength: 9 },
          ],
        },
      ],
    },
  },

  quotes: [
    {
      text: "Slaves got free food and free shelter in exchange for work. Now all they've done is got rid of the food and shelter deal. Give you dollars which you spend on food and shelter and you basically have nothing left. You're still a slave.",
      context: "Reformulation historique du salariat",
      tags: ["reframe", "esclavage", "salariat"],
      rhetorical_device: "Reframe historique provocateur",
      power_score: 8,
      chapter_idx: 1,
      highlight_words: ["still a slave", "food and shelter"],
    },
    {
      text: "Everything in life is people walking into rooms and saying things. That's what politics is. That's what business is. That's what the Senate is. That's what court is. Everything is people. Blah blah blah. Talking.",
      context: "Réduction radicale du pouvoir à la parole",
      tags: ["parole", "reduction", "eloquence"],
      rhetorical_device: "Réduction radicale + énumération",
      power_score: 10,
      chapter_idx: 2,
      highlight_words: ["walking into rooms", "saying things"],
    },
    {
      text: "'Um' and 'ah' will lose you a deal. All I did was repeat his question. You're saying, 'Ah, so you have time to think.' I'm repeating the question, so I have time to think.",
      context: "Technique concrète anti-hésitation",
      tags: ["technique", "eloquence", "vente"],
      rhetorical_device: "Tutoriel narré en direct",
      power_score: 9,
      chapter_idx: 2,
      highlight_words: ["um", "ah", "repeat his question"],
    },
    {
      text: "Speed defies gravity. If you get water in a bucket and you spin it around really fast, the water doesn't come out the bucket. Soon as you slow down, it falls out.",
      context: "Règle #1 — la vitesse comme loi universelle",
      tags: ["speed", "metaphore", "physique"],
      rhetorical_device: "Métaphore physique du seau",
      power_score: 9,
      chapter_idx: 3,
      highlight_words: ["speed defies gravity", "bucket"],
    },
    {
      text: "What's the first thing you fix? You fix oxygen. If you ain't got oxygen, the game's up. Nothing else is important. That's what this is. You fix the payments coming in.",
      context: "Analogie du payment gateway = oxygène",
      tags: ["priorite", "analogie", "business"],
      rhetorical_device: "Analogie vitale + priorisation forcée",
      power_score: 8,
      chapter_idx: 3,
      highlight_words: ["oxygen", "payments coming in"],
    },
    {
      text: "If you can find a loyal person, find them a job.",
      context: "Point 41 — inversion du recrutement classique",
      tags: ["recrutement", "loyaute", "operationnel"],
      rhetorical_device: "Inversion opérationnelle",
      power_score: 7,
      chapter_idx: 4,
      highlight_words: ["loyal person", "find them a job"],
    },
    {
      text: "If you aim for the moon, you'll get to the stars. If you aim for the stars, you'll get to the sky. If you aim for the sky, you won't get off the ground.",
      context: "Point 42 — gradation inversée du cliché",
      tags: ["ambition", "gradation", "cliche-renverse"],
      rhetorical_device: "Gradation en trois temps inversant un cliché",
      power_score: 9,
      chapter_idx: 4,
      highlight_words: ["moon", "stars", "sky", "won't get off"],
    },
    {
      text: "It's better to be irrationally self-confident than not. Don't be a bullshitter, but you need to be super self-confident.",
      context: "Point 43 — la ligne entre confiance et mensonge",
      tags: ["confiance", "distinction", "vente"],
      rhetorical_device: "Distinction fine + assertion",
      power_score: 8,
      chapter_idx: 4,
      highlight_words: ["irrationally self-confident", "not a bullshitter"],
    },
    {
      text: "Money cannot be made. It can only be taken from someone else. Money is like water and water is always moving. If you stand in the right place at the right time, you're going to get wet.",
      context: "Point 45 — la métaphore aquatique reprise de 'Dan the crackhead'",
      tags: ["argent", "metaphore", "philosophie-business"],
      rhetorical_device: "Métaphore aquatique + autorité mystifiée",
      power_score: 10,
      chapter_idx: 5,
      highlight_words: ["cannot be made", "taken", "like water"],
    },
    {
      text: "Tell people they can't have things all the time. If you tell people they can't have things, they want things.",
      context: "Point 47 — loi de la rareté",
      tags: ["vente", "rarete", "psychologie"],
      rhetorical_device: "Aphorisme + réversion",
      power_score: 8,
      chapter_idx: 5,
      highlight_words: ["can't have things", "want things"],
    },
    {
      text: "You already know what to do for your business. You already know how to make money. You're lazy.",
      context: "Point 50 — l'accusation directe",
      tags: ["accusation", "action", "provocation"],
      rhetorical_device: "Accusation directe en climax",
      power_score: 8,
      chapter_idx: 6,
      highlight_words: ["you already know", "you're lazy"],
    },
    {
      text: "You are passionate only about what's making you money. You are passionate for profit. You're not passionate about product.",
      context: "Point 51 — anti-cliché 'follow your passion'",
      tags: ["cliche-renverse", "argent", "vente"],
      rhetorical_device: "Substitution lexicale (passion → profit)",
      power_score: 8,
      chapter_idx: 6,
      highlight_words: ["passionate for profit", "not passionate about product"],
    },
    {
      text: "I once got told that chaos and opportunity are the same word in Japanese. I don't know if that's true, but I'm going to say it.",
      context: "Point 54 — l'aveu performatif du bullshitter",
      tags: ["aveu", "meta", "sophisme-assume"],
      rhetorical_device: "Aveu performatif désarmant",
      power_score: 10,
      chapter_idx: 6,
      highlight_words: ["don't know if that's true", "going to say it"],
    },
    {
      text: "If I'm not doing something which is either extremely difficult or extremely stressful, I'm in a perpetual state of crippling boredom. If I don't fight, if I'm not in a situation where I'm stressed or worried or concerned, I'm just perpetually bored. And boredom is crippling.",
      context: "Passage introspectif — la vraie cause de la discipline de Tate",
      tags: ["ennui", "aveu", "psychologie"],
      rhetorical_device: "Aveu introspectif rare",
      power_score: 10,
      chapter_idx: 7,
      highlight_words: ["crippling boredom", "perpetually bored"],
    },
    {
      text: "I was motivated to train probably about 25% of the time. The rest of the time, I went because I am disciplined.",
      context: "Chiffre pseudo-précis à l'appui de discipline > motivation",
      tags: ["discipline", "motivation", "chiffre"],
      rhetorical_device: "Pseudo-statistique crédibilisante",
      power_score: 9,
      chapter_idx: 8,
      highlight_words: ["25%", "disciplined"],
    },
    {
      text: "I want to be able to ice skate, but I don't want to be able to ice skate enough to go learn how to ice skate.",
      context: "Distinction want / want",
      tags: ["desir", "distinction", "test"],
      rhetorical_device: "Distinction sémantique en boucle",
      power_score: 8,
      chapter_idx: 8,
      highlight_words: ["want", "enough to go learn"],
    },
    {
      text: "Everyone wants money put on their lap. If you truly wanted money, you wouldn't be able to sleep until you had it.",
      context: "Test opérationnel du vrai désir",
      tags: ["desir", "test", "aphorisme"],
      rhetorical_device: "Aphorisme-test",
      power_score: 9,
      chapter_idx: 8,
      highlight_words: ["truly wanted", "wouldn't be able to sleep"],
    },
    {
      text: "One of the only things in this world you can control is your state of mind. If you can't control that, then you're just a feather in the wind and life's going to blow you around and you might land somewhere good. You might land in dog crap.",
      context: "Stoïcisme en langue populaire",
      tags: ["stoicisme", "controle", "metaphore"],
      rhetorical_device: "Métaphore de la plume + vulgarité contrastée",
      power_score: 8,
      chapter_idx: 8,
      highlight_words: ["state of mind", "feather in the wind"],
    },
    {
      text: "Motivation isn't real. Discipline is real.",
      context: "La formule fondamentale, sèche",
      tags: ["formule", "discipline", "motivation"],
      rhetorical_device: "Aphorisme binaire minimal",
      power_score: 9,
      chapter_idx: 8,
      highlight_words: ["Motivation", "Discipline"],
    },
    {
      text: "Being a man isn't about not feeling things. It's about acting the way you're supposed to act irregardless of how you feel.",
      context: "Définition de la virilité opérationnelle",
      tags: ["virilite", "definition", "action"],
      rhetorical_device: "Définition par négation + affirmation",
      power_score: 8,
      chapter_idx: 8,
      highlight_words: ["not feeling", "acting", "irregardless"],
    },
    {
      text: "Unmatched perspicacity coupled with sheer indefatigability makes me a feared opponent in any realm of human endeavor.",
      context: "Phrase signature — rupture lexicale finale",
      tags: ["signature", "vocabulaire", "clotures"],
      rhetorical_device: "Rupture lexicale (registre soutenu inséré)",
      power_score: 10,
      chapter_idx: 8,
      highlight_words: ["perspicacity", "indefatigability", "feared opponent"],
    },
    {
      text: "Working harder is never going to not help. If you have a problem, whether you're broke, whether you're out of shape, whether your friend dies, whether your girl leaves you, whether you're depressed, whatever it is, working harder is almost always the answer.",
      context: "Réponse universelle de Tate — travailler plus dur",
      tags: ["travail", "universel", "reponse-type"],
      rhetorical_device: "Anaphore whether + conclusion universelle",
      power_score: 7,
      chapter_idx: 8,
      highlight_words: ["working harder", "never not help"],
    },
  ],

  argumentation_kit: {
    how_to_defend: [
      {
        challenge: "Si on te dit : 'La technique repeat the question, c'est de la manipulation'",
        response: "Distinguer manipulation (créer une croyance fausse) et gestion cognitive (se donner du temps sans mentir)",
        technique: "Distinction éthique fine",
        example_response_text: "Reformuler la question, ce n'est pas manipuler — c'est se donner 3 secondes de traitement sans dégrader la perception de compétence. La manipulation, c'est produire une croyance fausse. Ici tu produis exactement la même réponse — tu prends juste le temps de la formuler proprement. Tout formateur en prise de parole enseigne ça.",
      },
      {
        challenge: "Si on te dit : 'Money is water est faux — l'innovation crée vraiment de la valeur nouvelle'",
        response: "Concéder pour l'innovation vraie + garder la validité pour le middleman (99% des cas)",
        technique: "Concession + isolation du sous-cas",
        example_response_text: "Tu as raison pour l'innovation profonde — un médicament qui guérit crée une valeur qui n'existait pas. Mais l'immense majorité des business (retail, agences, revente, services) sont des middlemen qui redirigent des flux existants. La métaphore de Tate est fausse pour Pasteur, vraie pour 99% des entrepreneurs. Utile pour les 99%.",
      },
      {
        challenge: "Si on te dit : 'Discipline > motivation est une opposition trop nette'",
        response: "Reconnaître le point neuroscientifique + garder l'utilité pratique de la formule",
        technique: "Nuance neuroscientifique + pragmatisme",
        example_response_text: "Neurosciencement, motivation et discipline sont couplées — la dopamine anticipative alimente la discipline, qui elle-même renforce la motivation. Mais dans le vécu immédiat, quand tu es dans le lit à 6h et que tu n'as pas envie, ce qui te fait sortir n'est pas la motivation — c'est le fait d'avoir pré-décidé. La formule de Tate est fausse comme théorie, utile comme protocole.",
      },
      {
        challenge: "Si on te dit : 'Aim way too high est irresponsable — tu vas te crasher'",
        response: "Redéfinir 'aim' comme direction, pas comme deadline chiffrée",
        technique: "Distinction vecteur / cible",
        example_response_text: "Aimer haut n'est pas se fixer un objectif chiffré déraisonnable à 6 mois. C'est orienter la direction. Un athlète qui vise l'or olympique ne se crashe pas — même s'il finit 4e, il finit beaucoup plus haut que celui qui a visé 'un bon niveau national'. L'ambition-vecteur crée le sillage, l'ambition-deadline crée le burnout. Deux choses différentes.",
      },
      {
        challenge: "Si on te dit : 'Le point 50 (miss makeup bimbo) blâme la victime — les gens ont des raisons de ne pas agir'",
        response: "Séparer les vraies contraintes structurelles (garde d'enfants, ressources) des simples résistances mentales",
        technique: "Séparation contrainte réelle / résistance mentale",
        example_response_text: "L'accusation de Tate marche pour les cas où la personne a le temps, l'accès et les moyens et ne fait rien — c'est fréquent. Elle est cruelle pour les cas où la personne fait déjà énormément et manque juste de bande passante. La bonne question à se poser : est-ce que j'ai vraiment essayé 90 minutes cette semaine, ou pas ?",
      },
    ],
    how_to_attack: [
      {
        target_claim: "Females are the ultimate status symbol",
        attack: "Réifie les femmes comme accessoires — position éthiquement disqualifiante et empiriquement fausse (les couples les plus stables ne sont pas basés sur le statut). Signale un cadre narcissique qui contamine le reste du propos.",
        angle: "Éthique",
      },
      {
        target_claim: "Everything is people walking into rooms and saying things",
        attack: "Réductionnisme utile mais faux : la parole seule ne fait pas gagner un procès (les faits, la loi, le dossier comptent), ne code pas un logiciel, ne guérit pas un patient. Utile comme métaphore, faux comme description.",
        angle: "Logique",
      },
      {
        target_claim: "Money cannot be made, only taken",
        attack: "Faux pour l'innovation qui augmente la productivité (agriculture moderne = 5x plus de nourriture par hectare). Le PIB mondial a été multiplié par 100 depuis 1800 — s'il ne s'était rien 'fait', ce serait impossible. Tate confond ses expériences de trader/middleman avec la totalité de l'économie.",
        angle: "Empirique",
      },
      {
        target_claim: "War can be profitable (contre les geeks Star Wars)",
        attack: "Modèle de business par harcèlement ciblé de communautés. Éthiquement problématique (cible des minorités inoffensives pour vendre) et légalement fragile (harassment). Non-généralisable à un business durable.",
        angle: "Éthique + Empirique",
      },
    ],
    how_to_rephrase: [
      {
        original: "You're still a slave.",
        softer: "La dépendance salariale actuelle a des caractéristiques structurelles qui rappellent les relations de servage antique — sans en avoir tous les traits.",
        harder: "Ta paie te loue à quelqu'un qui décide de ta semaine. Nomme ça comme tu veux — c'est de la location.",
        academic: "Le rapport salarial contemporain, comme le montre la sociologie du travail (Boltanski, Chiapello), maintient une forme de dépendance structurelle sur laquelle il est légitime d'interroger la liberté effective.",
      },
      {
        original: "Money is like water and water is always moving.",
        softer: "L'argent est une ressource en circulation permanente — l'important est de comprendre où circule le flux.",
        harder: "L'argent ne t'attend pas. Il coule. Positionne-toi ou reste sec.",
        academic: "La monnaie fonctionne comme une variable de flux plutôt que de stock — sa mécanique de circulation détermine largement où elle s'accumule (cf. Keynes, vélocité de la monnaie).",
      },
      {
        original: "You already know what to do. You're lazy.",
        softer: "Le savoir tacite dépasse presque toujours la mise en pratique — la vraie contrainte est rarement l'information.",
        harder: "Tu sais. Tu ne fais pas. Nomme ça honnêtement.",
        academic: "L'écart connu-fait ('knowing-doing gap', Pfeffer & Sutton) est un des blocages les plus documentés en gestion et développement personnel.",
      },
      {
        original: "Motivation isn't real. Discipline is real.",
        softer: "La motivation est intermittente ; construire des systèmes robustes est ce qui compense les creux inévitables de motivation.",
        harder: "La motivation est un mensonge que tu te racontes pour ne pas commencer. La discipline est ce qui te fait démarrer sans elle.",
        academic: "Les modèles contemporains de comportement (Fogg, Duckworth) montrent que l'ancrage habituel et l'infrastructure décisionnelle prédisent mieux la performance long terme que les états motivationnels ponctuels.",
      },
      {
        original: "Everyone wants money put on their lap. If you truly wanted money, you wouldn't be able to sleep.",
        softer: "Il existe une différence entre désir déclaratif et désir opérationnel — le second se signale par une modification concrète du quotidien.",
        harder: "Tu ne veux pas être riche. Tu veux ne pas être pauvre. Ce n'est pas pareil et ça se voit dans tes actes.",
        academic: "La distinction entre préférence exprimée et préférence révélée (Samuelson) reste l'un des outils analytiques les plus solides pour évaluer l'authenticité d'un désir.",
      },
    ],
    if_asked: [
      {
        question: "Comment appliquer 'repeat the question' concrètement en débat ?",
        best_response: "Trois formes : (1) reformulation neutre ('donc si je comprends bien, tu me demandes si...'), (2) reformulation amplifiée ('la vraie question sous-jacente, c'est...'), (3) reformulation redirigée ('la question intéressante, ce n'est pas X, c'est Y'). Les trois te donnent 2-4 secondes de temps de calcul sans un seul 'um'.",
        followup_moves: [
          "S'entraîner sur 20 questions banales chez soi avant utilisation live",
          "Attention au risque : reformulations trop fréquentes = perçues comme évitement",
        ],
      },
      {
        question: "Est-ce que 'discipline > motivation' est vrai ?",
        best_response: "Empiriquement, la formule est trompeuse : les études (Duckworth sur la grit, Ryan/Deci sur l'autodétermination) montrent que discipline et motivation sont couplées, pas opposées. Mais opérationnellement, elle est utile : elle déplace l'attention du ressenti (que tu ne contrôles pas) vers l'action (que tu contrôles). C'est un bon protocole, une fausse théorie.",
        followup_moves: [
          "Distinguer motivation intrinsèque (durable, alignée au sens) et motivation extrinsèque (fragile)",
          "Souligner que Tate lui-même a une motivation intrinsèque forte (fuite de l'ennui) qui alimente sa discipline",
        ],
      },
      {
        question: "Le 'chaos = opportunity en japonais' est-il vrai ?",
        best_response: "Non. Le mot japonais souvent cité pour crise (危機, kiki) contient bien un caractère qui signifie 'occasion' (機), mais celui-ci a plusieurs sens (occasion, mécanisme, moment) et l'idée que 'crise = danger + opportunité' est un mythe motivationnel occidental. Tate le sait — il l'admet dans la phrase suivante. C'est l'exemple typique de sa méthode : l'effet prime sur la vérité.",
        followup_moves: [
          "Souligner la méta : l'aveu ('I don't know if that's true') désarme la critique en avance",
          "Utile comme cas d'école pour étudier le sophisme assumé",
        ],
      },
      {
        question: "Faut-il vraiment 'aim way too high' ?",
        best_response: "Oui pour la direction (viser Everest fait progresser plus vite), non pour les deadlines chiffrées. La différence : orienter le vecteur (ambition) vs se fixer une échéance (planning). Tate mélange les deux — ses exemples ('$500M en 6 mois') sont les échéances-fantasmes qu'il dit lui-même éviter. Prendre le vecteur, laisser la deadline.",
        followup_moves: [
          "Illustrer par Boeing 787 (visé haut, livré tard) vs Concorde (visé haut, mal livré)",
          "Souligner : viser haut ne veut pas dire ignorer les incréments",
        ],
      },
      {
        question: "Pourquoi Tate confesse-t-il l'ennui chronique — c'est stratégique ou sincère ?",
        best_response: "Rare passage sincère. Il révèle que sa 'force de caractère' est en réalité une fuite d'un état pénible (crippling boredom). Ce n'est pas une critique de Tate — c'est un fait clinique intéressant : de nombreux hauts performeurs sont motivés par l'aversion au vide plutôt que par l'attrait du sommet. Ça n'invalide pas la méthode, ça en relativise la moralisation.",
        followup_moves: [
          "Lien avec la littérature sur la 'high-functioning ADHD' ou l'anxiété motrice",
          "Ne pas surinterpréter — Tate reste extrêmement productif quelle que soit la cause",
        ],
      },
      {
        question: "Comment utiliser 'perspicacity + indefatigability' au quotidien ?",
        best_response: "Perspicacité = capacité à voir avant les autres ce qui va compter. Indéfatigabilité = capacité à ne pas s'arrêter. Les deux ensemble battent tout — l'un sans l'autre est stérile (voir sans agir ou agir sans voir). Test : chaque semaine, note UNE chose que tu as vue avant les autres + UNE chose que tu n'as pas lâchée malgré la fatigue. Si ces deux cases sont remplies, tu es dans le combo.",
        followup_moves: [
          "S'entraîner à voir : lire 30 min/jour d'un domaine étranger",
          "S'entraîner à ne pas lâcher : une seule habitude non négociable en 90 jours",
        ],
      },
    ],
  },

  fallacies: [
    {
      original_claim: "Females are the ultimate status symbol.",
      fallacy_type: "objectification + hasty generalization",
      why_fallacious: "Réifie une catégorie humaine comme accessoire de statut. Empiriquement faux : les études sur satisfaction masculine (Roberts, Aron) montrent que la connexion émotionnelle et la sécurité relationnelle prédisent mieux le bien-être que le nombre ou l'apparence des partenaires.",
      steelman: "Dans certains sous-groupes hyper-compétitifs (clubs, réseaux sociaux), l'entourage féminin fonctionne effectivement comme signal costly (Zahavi). L'observation empirique locale n'est pas fausse — c'est l'universalisation qui l'est.",
      nuance: "Vrai comme observation dans les jeux de statut ostentatoire — faux comme description de ce qui fait une vie masculine bonne. Confusion entre signal externe et satisfaction interne.",
      counter_argument: "Les hommes en couple long-terme rapportent une satisfaction supérieure à ceux qui accumulent des partenaires (méta-analyses de Kansas et Michigan sur 10 000+ hommes). Le 'signal' de Tate produit du statut social mais pas de bien-être.",
      severity: "high",
    },
    {
      original_claim: "Money cannot be made. It can only be taken from someone else.",
      fallacy_type: "zero-sum fallacy",
      why_fallacious: "Traite l'économie comme un stock fixe alors que le PIB mondial est passé d'environ 1 trillion (1800) à plus de 100 trillion (2024). Si l'argent ne pouvait qu'être 'pris', la croissance productive serait impossible.",
      steelman: "Pour les activités de middleman (99% des business selon Tate), la métaphore capture une vérité opérationnelle : tu captures un flux, tu ne crées pas ex nihilo. C'est utile pour cadrer une stratégie de positionnement.",
      nuance: "Vrai pour la revente, le trading, l'intermédiation. Faux pour l'innovation productive (agriculture, médicaments, logiciels qui font gagner du temps). Pour Auguste : selon quelle activité tu vises, la métaphore s'applique ou pas.",
      counter_argument: "L'invention de la pénicilline a créé une valeur qui n'existait pas — elle n'a rien 'pris' à personne. Idem pour Google Search en 1998 : personne n'avait ce service, l'utilité produite est nette et nouvelle.",
      severity: "medium",
    },
    {
      original_claim: "Motivation isn't real. Discipline is real.",
      fallacy_type: "false dichotomy",
      why_fallacious: "Oppose deux concepts qui sont en réalité en boucle de renforcement mutuel. La motivation intrinsèque (autodétermination) prédit la persévérance et donc la discipline durable ; la discipline exécutée produit des accomplissements qui alimentent la motivation.",
      steelman: "Comme heuristique protocolaire — 'n'attends pas d'avoir envie pour agir' — la formule est extrêmement efficace et supérieure au discours motivationnel du 'trouve ta passion'.",
      nuance: "Vrai comme protocole quotidien (agir sans dépendre de l'humeur), faux comme théorie psychologique (la boucle discipline-motivation est bien établie).",
      counter_argument: "Deci & Ryan (Self-Determination Theory) — la motivation intrinsèque autonome prédit la meilleure discipline durable, mieux que la contrainte externe pure. Duckworth (Grit) — la grit inclut passion (motivation) et perseverance (discipline).",
      severity: "medium",
    },
    {
      original_claim: "Tell people they can't have things (rareté fabricée).",
      fallacy_type: "manipulation prescrite comme tactique",
      why_fallacious: "La rareté fabriquée (fake scarcity) est un mensonge implicite quand elle n'est pas réelle. Éthiquement problématique et légalement encadrée dans plusieurs juridictions (dark patterns, DGCCRF, FTC).",
      steelman: "La psychologie de la rareté est réelle (Cialdini) et une rareté authentique est un signal utile — l'exclusivité informe l'acheteur sur la valeur. Le problème n'est pas la rareté, c'est le mensonge sur son existence.",
      nuance: "Rareté vraie = signal légitime. Rareté simulée = manipulation. Tate confond les deux et normalise la seconde comme tactique standard.",
      counter_argument: "Les entreprises qui construisent la confiance long terme (Patagonia, Vanguard) ne simulent pas de rareté — leur croissance repose sur la fiabilité. La rareté fabriquée maximise la conversion court terme et détruit la marque long terme.",
      severity: "medium",
    },
    {
      original_claim: "Chaos and opportunity are the same word in Japanese.",
      fallacy_type: "false authority (aveu inclus)",
      why_fallacious: "Fausse étymologie inventée pour appuyer une thèse motivationnelle. Le kanji 機 (ki) dans 危機 (kiki, crise) signifie 'mécanisme/moment' — pas 'opportunité' de manière univoque. Tate l'admet dans la phrase suivante — ce qui rend le sophisme performatif.",
      steelman: "L'aveu ('I don't know if that's true, but I'm going to say it') est en soi un dispositif rhétorique audacieux — il crée une ironie qui désarme la critique. C'est un cas d'école de sophisme assumé.",
      nuance: "Comme information linguistique : faux. Comme métaphore inspirante : elle a une utilité motivationnelle réelle. Comme méta-rhétorique : Tate montre en direct comment il fabrique une autorité — ce qui est presque une leçon offerte à l'auditeur.",
      counter_argument: "Cette 'étymologie' est un mythe motivationnel occidental documenté depuis Kennedy en 1959. Les linguistes japonais eux-mêmes rejettent l'interprétation. Utile pour inspirer, dangereux si présenté comme fait.",
      severity: "low",
    },
    {
      original_claim: "If you're depressed and you have unlimited options, how do you have time to be depressed?",
      fallacy_type: "false dilemma + minimisation clinique",
      why_fallacious: "Traite la dépression comme un choix ou une paresse temporelle. Confond humeur triste ponctuelle et trouble dépressif majeur (MDD), qui a des marqueurs biologiques et n'est pas un problème de time management.",
      steelman: "Le point utile : rumination + inaction aggravent l'humeur, et un cadre extérieur exigeant peut effectivement briser la spirale. C'est cohérent avec les recommandations en TCC (behavioral activation).",
      nuance: "Vrai comme prescription pour les dépressions légères/situationnelles. Nuisible et faux pour les dépressions cliniques majeures qui nécessitent parfois traitement médicamenteux et thérapie.",
      counter_argument: "OMS 2023 : plus de 280 millions de personnes souffrent de dépression clinique dans le monde. Le mécanisme n'est pas 'trop de temps libre' — c'est une pathologie multifactorielle. La minimisation retarde la prise en charge et aggrave les issues.",
      severity: "high",
    },
    {
      original_claim: "You are passionate for profit only. Not passionate about product.",
      fallacy_type: "false dichotomy",
      why_fallacious: "Oppose deux motivations qui coexistent chez les fondateurs les plus performants. Passion produit (obsession pour la qualité) et passion profit (obsession pour la marge) sont complémentaires — les meilleurs les combinent.",
      steelman: "Le point vise à contrer le cliché 'follow your passion' qui pousse les gens à monter des business non-viables sur des sujets qu'ils aiment mais qui ne se vendent pas. Vrai comme contre-poison.",
      nuance: "Pour Auguste : le vrai principe est 'passion pour un marché où ton talent produit de la marge' — ni passion produit pure, ni passion profit pure.",
      counter_argument: "Steve Jobs, Yvon Chouinard (Patagonia), Elon Musk (Tesla) — cas classiques de passion-produit ayant produit énormément de profit. La formule de Tate ignore que la passion-produit peut être un moteur de différenciation.",
      severity: "medium",
    },
  ],

  stats: [
    {
      number: "25%",
      label: "du temps où Tate dit avoir été motivé à s'entraîner (sur 12 ans, 5h/jour, 6 j/sem)",
      source: "Tate — vidéo",
      context: "Base chiffrée de l'argument discipline > motivation",
      visual: "percent",
    },
    {
      number: "12",
      label: "années de kickboxing pro comme base autobiographique de la thèse",
      source: "Tate — 'I was a 4-time kickboxing world champion. For 12 years I trained 5 hours a day, 6 days a week'",
      context: "Preuve par volume d'expérience",
      visual: "count-up",
    },
    {
      number: "$150k",
      label: "salaire annuel du 'manager BMW' qualifié de non-succès",
      source: "Tate — vidéo",
      context: "Chiffre-repère qui recadre ce que 'success' veut dire",
      visual: "comparison",
    },
    {
      number: "99%",
      label: "des gens qui échouent à la vente à cause d'un 'um' ou d'un 'ah' selon Tate",
      source: "Tate — vidéo",
      context: "Hyperbole crédibilisante pour vendre la technique repeat the question",
      visual: "percent",
    },
    {
      number: "10 000+",
      label: "seuil de followers en dessous duquel Tate refuse le beef",
      source: "Tate — 'I will only beef with someone if they have more than 10,000 followers'",
      context: "Point 52 — critère opérationnel de la guerre online",
      visual: "count-up",
    },
    {
      number: "15 000",
      label: "ventes du PhD course revendiquées suite au beef Star Wars",
      source: "Tate — vidéo",
      context: "Preuve par récit du ROI d'une war stratégique",
      visual: "count-up",
    },
  ],

  comparisons: [
    {
      title: "Manager BMW / Real dawn (selon Tate)",
      left: {
        label: "Manager BMW",
        items: [
          "Important seulement dans son immeuble",
          "Femme insatisfaite",
          "Envoie des emails à son staff",
          "Personne ne le respecte hors du bureau",
        ],
      },
      right: {
        label: "Real dawn",
        items: [
          "Freedom géographique + temporelle",
          "Réseau qui décroche ses appels",
          "Body language de danger",
          "Femmes comme signal de statut",
        ],
      },
    },
    {
      title: "Want (déclaratif) / Want (opérationnel)",
      left: {
        label: "Want déclaratif",
        items: [
          "Je veux savoir patiner",
          "Je veux être riche",
          "Je veux perdre du poids",
          "Ne modifie rien au quotidien",
        ],
      },
      right: {
        label: "Want opérationnel",
        items: [
          "Prend des cours 3x/semaine",
          "Peut pas dormir tant qu'il n'a pas l'argent",
          "Change son alimentation aujourd'hui",
          "Modifie tout le quotidien",
        ],
      },
    },
    {
      title: "Discipline / Motivation",
      left: {
        label: "Discipline",
        items: [
          "Indépendante de l'humeur",
          "S'exécute pré-décidée",
          "S'active à 6h dans le noir",
          "25% du temps sans envie",
        ],
      },
      right: {
        label: "Motivation",
        items: [
          "Dépend de l'humeur du jour",
          "Se cherche dans la playlist",
          "Attend le 'right mood'",
          "Fleeting — s'évapore avant l'action",
        ],
      },
    },
  ],

  devices: [
    {
      name: "Réduction radicale",
      example_text: "Everything in life is people walking into rooms and saying things.",
      effect: "Simplifie un système complexe à une seule mécanique — donne l'impression d'avoir compris",
      why_it_works: "L'auditeur reçoit un modèle mental compact qui semble expliquer beaucoup — sensation de compréhension = adhésion",
    },
    {
      name: "Métaphore physique",
      example_text: "Speed defies gravity. If you get water in a bucket and you spin it around really fast, the water doesn't come out.",
      effect: "Rend tangible un principe abstrait via une expérience accessible",
      why_it_works: "L'auditeur peut mentalement simuler l'expérience — l'image devient preuve",
    },
    {
      name: "Gradation inversée",
      example_text: "If you aim for the moon, you'll get to the stars. If you aim for the stars, you'll get to the sky. If you aim for the sky, you won't get off the ground.",
      effect: "Renouvelle un cliché en lui ajoutant un palier d'échec",
      why_it_works: "L'auditeur attend la version connue — la rupture au 3e temps produit l'attention",
    },
    {
      name: "Aveu performatif",
      example_text: "I don't know if that's true, but I'm going to say it.",
      effect: "Désarme la critique en s'attaquant soi-même — rend la suite plus crédible par contraste",
      why_it_works: "L'auditeur ne peut plus attaquer sur ce point — l'orateur a déjà tout concédé",
    },
    {
      name: "Tutoriel narré en direct",
      example_text: "Oh, well, um, okay. So, um, uh, why? How's the flux capacitor work?",
      effect: "Transforme un conseil abstrait en démonstration vivante",
      why_it_works: "L'auditeur voit le mauvais exemple et le bon — apprentissage par contraste",
    },
    {
      name: "Pseudo-statistique",
      example_text: "25% of the time motivated.",
      effect: "Donne du grain à une affirmation qui sans chiffre serait molle",
      why_it_works: "Le chiffre spécifique (25%) semble plus crédible qu'un 'la plupart du temps'",
    },
    {
      name: "Rupture lexicale finale",
      example_text: "Unmatched perspicacity coupled with sheer indefatigability makes me a feared opponent in any realm of human endeavor.",
      effect: "Démontre la maîtrise des registres — finale impactante",
      why_it_works: "Le contraste avec le registre oral précédent signale une réserve intellectuelle — crédibilité rétroactive",
    },
    {
      name: "Métaphore aquatique récurrente",
      example_text: "Money is like water. Speed defies gravity (water in bucket).",
      effect: "Crée un système d'images cohérent qui structure mentalement le discours",
      why_it_works: "L'unification thématique aide la mémorisation et donne une impression de doctrine cohérente",
    },
    {
      name: "Anaphore whether",
      example_text: "Whether you're broke, whether you're out of shape, whether your friend dies, whether your girl leaves you.",
      effect: "Enveloppe toutes les objections possibles — laisse une seule réponse",
      why_it_works: "L'exhaustivité apparente ferme les échappatoires — l'auditeur ne peut plus dire 'oui mais dans mon cas'",
    },
  ],

  analogies: [
    {
      source: "Water in bucket (mouvement circulaire)",
      used_for: "Speed defies gravity — pourquoi la vitesse tient les problèmes ensemble",
      strength: 8,
      why_it_works: "Expérience physique tangible — chacun peut la simuler mentalement",
    },
    {
      source: "Oxygène = payment gateway",
      used_for: "Priorisation en cas de crise business",
      strength: 8,
      why_it_works: "Vital + immédiat — impossible de discuter la priorité de l'oxygène",
    },
    {
      source: "James Bond outnumbered",
      used_for: "Illustration de la confiance irrationnelle",
      strength: 7,
      why_it_works: "Icône culturelle universelle — le mode 'I'm me, I'm a G' est immédiatement compréhensible",
    },
    {
      source: "Dan the crackhead (autorité mystifiée)",
      used_for: "Introduire la métaphore money = water",
      strength: 6,
      why_it_works: "Le mentor improbable (crackhead) crée une accroche — la sagesse populaire est plus crédible que la théorie académique",
    },
    {
      source: "9/11 → assurance annulation vol",
      used_for: "Illustrer chaos = opportunity avec un cas historique",
      strength: 7,
      why_it_works: "Événement collectif marquant — l'auditeur peut voir la mécanique de monétisation dans un cadre connu",
    },
    {
      source: "Ferrari race vs push bike",
      used_for: "Impossibilité de gagner sans upgrade de son personnage",
      strength: 7,
      why_it_works: "Image cinétique immédiate — la différence de véhicule rend visible la différence de préparation",
    },
  ],

  frameworks: [
    {
      name: "Le protocole 'Repeat the question'",
      when_to_use: "Question difficile en live (interview, débat, négociation)",
      steps: [
        "Étape 1 : recevoir la question sans dire 'um'",
        "Étape 2 : reformuler à voix haute ('donc si je comprends bien, tu me demandes X ?')",
        "Étape 3 : profiter des 3 secondes gagnées pour construire la réponse",
        "Étape 4 : livrer la réponse construite avec débit régulier",
      ],
      warning: "Utilisé trop souvent (>2 fois par question), perçu comme évitement",
    },
    {
      name: "Le protocole 'Speed = oxygène'",
      when_to_use: "Crise business ou personnelle (payment gateway down, échec de projet)",
      steps: [
        "Étape 1 : identifier l'artère vitale unique (le 'oxygène' du système)",
        "Étape 2 : mettre 80% des ressources dessus, 20% sur le reste",
        "Étape 3 : accepter le mess temporaire sur les fonctions non-vitales",
        "Étape 4 : une fois l'artère rétablie, cleaner en manuel — jamais l'inverse",
      ],
      warning: "Nécessite avoir identifié à froid ce qu'est l'oxygène — sinon panique de priorisation en crise",
    },
    {
      name: "Le test 'Want vs want'",
      when_to_use: "Face à un objectif déclaré (le sien ou celui d'un autre)",
      steps: [
        "Étape 1 : reformuler l'objectif ('tu veux X')",
        "Étape 2 : identifier UN comportement quotidien nécessaire à X",
        "Étape 3 : demander 'est-ce que ce comportement est présent dans ta vie actuelle ?'",
        "Étape 4 : si non, l'objectif est déclaratif — pas encore opérationnel. Rendre visible sans juger.",
      ],
      warning: "Peut être vécu comme culpabilisant — utiliser sur soi d'abord, sur les autres avec ménagement",
    },
    {
      name: "Chaos → opportunity mapping",
      when_to_use: "Face à un mess (interne ou marché externe)",
      steps: [
        "Étape 1 : décrire le chaos en une phrase factuelle",
        "Étape 2 : lister 3 catégories d'acteurs affectés",
        "Étape 3 : identifier UN besoin nouveau créé par le chaos",
        "Étape 4 : proposer une offre minimale pour ce besoin (MVP en 48h)",
      ],
      warning: "Éthiquement : ne pas exploiter la souffrance (ex: chaos = catastrophe humaine). Le framework s'applique aux chaos structurels, pas aux tragédies.",
    },
  ],

  drills: [
    {
      name: "20 questions repeat-the-question",
      duration: "5 jours × 15 minutes",
      instructions: [
        "Prendre 20 questions banales préparées (ex: pourquoi Paris ? comment tu fais X ? etc.)",
        "S'entraîner à reformuler chaque question avant de répondre",
        "Enregistrer 5 min chaque soir, écouter et compter les 'um'",
        "Objectif jour 5 : moins de 3 'um' sur 15 minutes de discours",
      ],
      difficulty: 2,
    },
    {
      name: "Chaos monetization",
      duration: "1 semaine",
      instructions: [
        "Chaque matin, choisir un événement chaotique du jour (news, sa propre vie)",
        "Écrire en 3 minutes une offre monétisable qui répondrait à ce chaos",
        "Fin de semaine : sélectionner l'offre la plus réalisable et la tester réellement 4h",
        "Documenter le résultat même si zéro vente",
      ],
      difficulty: 3,
    },
    {
      name: "Rupture lexicale",
      duration: "10 jours",
      instructions: [
        "Identifier son registre oral habituel (mots-outils, fillers)",
        "Choisir 3 mots de registre soutenu par semaine (perspicacité, indéfectible, éloquence, etc.)",
        "Les placer dans UNE prise de parole publique par semaine, à un moment climax",
        "Bilan : quel effet sur l'attention de l'audience ?",
      ],
      difficulty: 3,
    },
    {
      name: "Discipline sans motivation (30 jours)",
      duration: "30 jours",
      instructions: [
        "Choisir UNE action non négociable (30 min de sport, 500 mots écrits, etc.)",
        "L'exécuter chaque jour sans vérifier son 'niveau de motivation' avant",
        "Tenir un journal binaire : fait / pas fait — pas de commentaire émotionnel",
        "Jour 30 : compter les jours faits — objectif >= 27/30",
      ],
      difficulty: 4,
    },
  ],

  related: {
    videos: ["AG1vvPVkHC8", "d8FH8K7n0GE", "cZwULaBA9Bw"],
    debates: ["discipline-motivation", "capital-humain-modernite"],
  },
};

if (typeof CONTENT_REGISTRY !== 'undefined') CONTENT_REGISTRY["Gv39IoU5Z5s"] = CONTENT_Gv39IoU5Z5s;
