// /mindmap/content/P4rkjwaa6so.js
// Deep content for Andrew Tate — long-form podcast
// "Compétition, Argent, Purpose"
// Source: fiche-tate-podcast-competition-money-purpose.md (638 lines)
// Transcript: P4rkjwaa6so-tate-podcast-competition-money-purpose-raw.txt (~15 800 words)

const CONTENT_P4rkjwaa6so = {
  id: "P4rkjwaa6so",
  slug: "tate-podcast-competition-money-purpose",
  title: "Compétition, Argent, Purpose (long-form)",
  speaker: "Andrew Tate",
  format: "interview podcast · long-format",
  word_count: 15800,
  language: "en",

  // ============================================================
  // 1. EXECUTIVE LAYER
  // ============================================================
  hook: "You're too slow — and you're going to lose against people like me.",
  thesis: "L'homme moderne perd parce qu'il est lent, isolé, distrait par le confort, et manipulé à croire des mensonges ; la sortie passe par une accountability totale (100 %), une vitesse d'exécution supérieure, un network de prédateurs, la conversion de la douleur en actif, et le refus du bonheur au profit du purpose.",
  key_takeaways: [
    "100 % accountability : chaque bien et chaque mal qui t'arrive est *ta* faute — c'est la seule position depuis laquelle tu as un levier.",
    "Speed > perfection : ce que tu prétends « prendre du temps » prend le temps que ta paresse lui alloue.",
    "Active income avant passive : parler de revenus passifs quand tu n'as rien = paresse maquillée.",
    "Ton network = ton QI de vie : tu es la somme des 5 personnes avec qui tu passes le plus de temps.",
    "Confidence ← competence, jamais l'inverse : aucune affirmation n'égale une compétence prouvée.",
    "Purpose = struggle + conquer, pas bonheur : le bonheur est un frame féminin, la conquête est un devoir masculin.",
    "Attention = monnaie : 0,25 s pour capter, sinon la valeur ne se monétise pas.",
    "Trauma = building blocks : Batman est Batman parce qu'on a tué ses parents.",
    "Value exchange partout : amitié, business, relation — sans échange, tu es en dette silencieuse.",
    "Le stress a un effet placebo : ton récit intérieur est pharmacologie active.",
  ],

  // ============================================================
  // 2. CHAPTERS
  // ============================================================
  chapters: [
    {
      idx: 1,
      title: "Chess = 100 % accountability",
      summary: "Ouverture par l'aphorisme d'attaque (« you're too slow »). Le jeu d'échecs comme modèle de vie : aucune chance, chaque défaite = erreur diagnosticable. Pose le cadre fondamental de la responsabilité totale.",
      key_quote: "It's 100% accountability with no luck. That's what's so important about learning chess.",
      duration_estimate: "0:00-4:30",
    },
    {
      idx: 2,
      title: "Matrix attacks — la preuve autobiographique",
      summary: "Application du 100 % accountability à son propre cas : quand la Matrix ferme ses banques, appelle ses ex, ban ses comptes, il dit « c'est ma faute ». Non pas moralement mais stratégiquement — pour retrouver du levier.",
      key_quote: "I'm sitting there going, 'This is my fault. All of this is me. I got here.'",
      duration_estimate: "4:30-8:00",
    },
    {
      idx: 3,
      title: "Forrest Gump feather — cause ou effet",
      summary: "Analogie du début de Forrest Gump : la plume qui se pose. Forrest est la plume, la vie le pousse. Modèle de vie majoritaire. L'alternative : être le vent, arriver aux circonstances.",
      key_quote: "If you let life come to you, you're going to be living inside of a matrix.",
      duration_estimate: "8:00-11:30",
    },
    {
      idx: 4,
      title: "Matrix programming — cui bono",
      summary: "Test universel de toute croyance imposée : à qui profite ? Applique à l'université, aux médias, aux normes. « The whole world's about power. »",
      key_quote: "Why do you want me to believe this? Do you want me to believe this because it's good for me or is it because it's good for you?",
      duration_estimate: "11:30-15:00",
    },
    {
      idx: 5,
      title: "Purpose > fun — conquête comme drive divin",
      summary: "Rejet du concept de fun (« pour femmes et enfants »). Conquérir = construire (skyscrapers, roads, family), pas seulement dominer. Les femmes veulent un homme compétent qui les décharge de la pensée.",
      key_quote: "Fun is for women and children.",
      duration_estimate: "15:00-20:00",
    },
    {
      idx: 6,
      title: "Ignorance et bonheur fragile",
      summary: "Concession honnête : les ignorants peuvent être heureux jusqu'à ce que ça ne suffise plus. Alors la ruine est totale car ils n'ont pas d'outils. Culmine en « I am the circumstance ».",
      key_quote: "I'm not subject to circumstance. Tate arrives and circumstances change.",
      duration_estimate: "20:00-25:00",
    },
    {
      idx: 7,
      title: "War Room — network de prédateurs",
      summary: "Doctrine de la sélection sociale. Au sommet de la montagne, personne n'a tout ; il faut un network de prédateurs formés. Contraste toi/Tate : tu lis un livre / lui reçoit 25 messages et fait un deal de 5 M$ en 15 min.",
      key_quote: "You are the sum of the five people you spend the most time with. You will always lose against a network.",
      duration_estimate: "25:00-32:00",
    },
    {
      idx: 8,
      title: "Éduquer dur — Russie, Khabib, montagnes",
      summary: "Application familiale du principe trauma = building blocks. Refus d'élever des enfants mous. Vise l'éducation dure comme fondation. Assumé mais discutable (angle critique).",
      key_quote: "I want them growing up in deep Russia, in the mountains with goats, running in the snow barefoot.",
      duration_estimate: "32:00-38:00",
    },
    {
      idx: 9,
      title: "Respect > amour — le bonheur masculin",
      summary: "Théorie du bonheur masculin : chercher le respect, pas l'amour. Le respect vient de la décision, du refus, de la performance. Reformulation majeure de la valeur masculine.",
      key_quote: "Your happiness as a man comes from feeling respected over feeling loved.",
      duration_estimate: "38:00-44:00",
    },
    {
      idx: 10,
      title: "Speed music track — preuve de vitesse",
      summary: "Anecdote emblème : le morceau écrit en 2h30 pour prouver à un ami que « prendre 6 mois » = paresse. Millions de vues. Prouve : la speed est le multiplicateur ultime, plus grand que le talent.",
      key_quote: "I made a song in 2 and 1/2 hours. Speed works. Just do it all at once.",
      duration_estimate: "44:00-52:00",
    },
    {
      idx: 11,
      title: "Money — active > passive, coffee shop, unreality",
      summary: "Doctrine financière complète. Étape 1 : active income max. Étape 2 : passivation. Étape 3 : buying freedom. Coffee shop exercise (décoder chaque commerce). Au-dessus d'un seuil, l'argent devient irréel (3,2 M$ de Ferraris, 400k £ pour voir Bilzerian).",
      key_quote: "Business is other people's money.",
      duration_estimate: "52:00-1:08:00",
    },
    {
      idx: 12,
      title: "Attention economy & 0,25 s",
      summary: "L'attention comme dernière monnaie. TikTok = 0,25 s pour tester. L'algorithme est ton co-fondateur. Toute stratégie qui ne l'intègre pas est morte-née.",
      key_quote: "The most valuable thing that exists is attention.",
      duration_estimate: "1:08:00-1:15:00",
    },
    {
      idx: 13,
      title: "Belief creates action — 4-minute mile",
      summary: "Histoire de Roger Bannister. La barrière était mentale. Après lui, 10 personnes ont fait le mile en 3 semaines. Loi de la croyance-plafond. Corollaire : la confidence vient de la competence, jamais de l'affirmation.",
      key_quote: "The reason I'm confident is because I'm good at everything.",
      duration_estimate: "1:15:00-1:22:00",
    },
    {
      idx: 14,
      title: "Trauma = building blocks (Batman) + stoïcisme civique",
      summary: "Théodicée de la douleur passée. Batman comme mythe. Chaque worst = building block. Puis retournement : les hommes faibles émotionnellement sont les plus dangereux (school shooters). Le stoïcisme = service à la civilisation.",
      key_quote: "Bad things happened to Batman. They killed his parents. That's why he's Batman.",
      duration_estimate: "1:22:00-1:35:00",
    },
  ],

  // ============================================================
  // 3. ARGUMENT TREE
  // ============================================================
  argument_tree: {
    root: {
      claim: "L'homme moderne perd parce qu'il est lent, isolé, distrait ; la sortie = 100% accountability + vitesse + network + purpose + reframe de la douleur.",
      children: [
        {
          claim: "100 % accountability est la fondation opérationnelle",
          type: "premise",
          strength: 9,
          evidence: ["Chess : aucune chance, chaque défaite diagnosticable", "Matrix attaque Tate : il dit 'my fault' pour retrouver du levier"],
          children: [
            {
              claim: "Sans accountability, aucun levier",
              type: "premise",
              strength: 8,
              evidence: ["Blâmer les circonstances = position passive"],
              children: [
                { claim: "Feather de Forrest Gump = modèle passif majoritaire", type: "analogy", strength: 9 },
                { claim: "« I am the circumstance » = position active", type: "example", strength: 8 },
              ],
            },
            {
              claim: "Chess metaphor prouve que la maîtrise = 100% responsabilité",
              type: "analogy",
              strength: 8,
              evidence: ["Aucune carte, aucune chance, aucun dé"],
            },
          ],
        },
        {
          claim: "La vitesse est un multiplicateur plus grand que le talent",
          type: "premise",
          strength: 9,
          evidence: ["Morceau écrit en 2h30 → millions de vues", "Décisions financières en 15 min via network"],
          children: [
            {
              claim: "La lenteur est une paresse déguisée en perfection",
              type: "premise",
              strength: 8,
              children: [
                { claim: "L'ami musicien : 6 mois → rien", type: "example", strength: 9 },
                { claim: "Test de 3 heures : livrer maintenant, imparfait, mais fini", type: "example", strength: 7 },
              ],
            },
            {
              claim: "Lire un livre = 8h qui aurait pu produire 10 décisions",
              type: "premise",
              strength: 6,
              evidence: ["« By the time you were done reading the book, the moves have been made »"],
            },
          ],
        },
        {
          claim: "L'argent suit une progression obligatoire : active → passive → freedom",
          type: "premise",
          strength: 8,
          children: [
            {
              claim: "Active income avant passive",
              type: "premise",
              strength: 9,
              evidence: ["Demander du passif quand tu n'as rien = signal de paresse"],
              children: [
                { claim: "Commission-only teste ta vraie foi", type: "example", strength: 8 },
                { claim: "18h/j saturent d'abord, tu optimises ensuite", type: "premise", strength: 7 },
              ],
            },
            {
              claim: "Au-delà d'un seuil, l'argent devient irréel",
              type: "premise",
              strength: 7,
              evidence: ["3,2 M$ de Ferraris", "400k £ pour voir Bilzerian 4h", "1 M$ pour un lifestyle top"],
            },
            {
              claim: "Free money = wealth transfer aux asset owners",
              type: "premise",
              strength: 8,
              children: [
                { claim: "1000 £ à chaque UK citizen → finit chez Bezos", type: "example", strength: 8 },
                { claim: "La solution = devenir asset owner", type: "premise", strength: 7 },
              ],
            },
          ],
        },
        {
          claim: "Ton network = ton QI de vie et ton coefficient de vitesse",
          type: "premise",
          strength: 9,
          evidence: ["War Room : 25 messages au réveil, décisions à 5M$ en 15 min"],
          children: [
            {
              claim: "Tu es la somme des 5 personnes avec qui tu passes le plus de temps",
              type: "premise",
              strength: 9,
            },
            { claim: "Tu perds toujours contre un network", type: "premise", strength: 8 },
            { claim: "Les prédateurs formés partagent l'info en temps réel", type: "example", strength: 8 },
          ],
        },
        {
          claim: "Le purpose remplace la quête du bonheur",
          type: "premise",
          strength: 8,
          children: [
            {
              claim: "Fun est féminin, purpose est masculin",
              type: "premise",
              strength: 6,
              children: [
                { claim: "Les femmes veulent un homme compétent (pas fun)", type: "example", strength: 7 },
                { claim: "Skyscrapers, roads, family = conquête sacrée", type: "analogy", strength: 8 },
              ],
            },
            {
              claim: "Respect > amour dans le bonheur masculin",
              type: "premise",
              strength: 8,
            },
            { claim: "Ignorance = bonheur, mais fragile face à l'adversité", type: "premise", strength: 7 },
          ],
        },
        {
          claim: "La confidence vient de la competence, jamais de l'affirmation",
          type: "premise",
          strength: 9,
          evidence: ["« I'm confident because I'm competent »"],
          children: [
            { claim: "Devenir objectivement bon dans un domaine mesurable", type: "premise", strength: 8 },
            { claim: "Ne faire que ce qu'on est bon à faire", type: "premise", strength: 7 },
            { claim: "4-minute mile : la croyance était le plafond, pas la biologie", type: "analogy", strength: 8 },
          ],
        },
        {
          claim: "La douleur passée est ton actif principal",
          type: "premise",
          strength: 8,
          evidence: ["Batman : parents tués → Batman", "« The best things ever happened to me are the worst »"],
          children: [
            { claim: "Chaque douleur passée = capacité future à supporter", type: "premise", strength: 8 },
            { claim: "Un homme sans trauma est fragile", type: "premise", strength: 6 },
            { claim: "Trauma reframing : lister 3 compétences acquises par la pire période", type: "example", strength: 7 },
          ],
        },
        {
          claim: "Le stoïcisme émotionnel est un service civique, pas un choix perso",
          type: "premise",
          strength: 7,
          evidence: ["Les hommes faibles émotionnellement = school shooters, violeurs"],
          children: [
            {
              claim: "Sois froid ou sois violent — pas de troisième option",
              type: "premise",
              strength: 6,
              children: [
                { claim: "Les émotions non-contrôlées cassent tout", type: "premise", strength: 6 },
                { claim: "Le stress a un effet placebo — étude citée", type: "evidence", strength: 7 },
              ],
            },
          ],
        },
        {
          claim: "L'attention est la monnaie ultime de l'ère TikTok",
          type: "premise",
          strength: 9,
          evidence: ["0,25 s de test", "Rihanna makeup brand : attention → monétisation totale"],
          children: [
            { claim: "L'accroche avant le produit — test des 3 secondes", type: "example", strength: 8 },
            { claim: "L'algorithme est ton co-fondateur", type: "premise", strength: 7 },
          ],
        },
      ],
    },
  },

  // ============================================================
  // 4. QUOTES
  // ============================================================
  quotes: [
    // Accountability & mental frame
    {
      text: "You are too slow and you are going to lose against people like me.",
      context: "Ouverture — aphorisme d'attaque",
      tags: ["speed", "provocation", "aphorisme"],
      rhetorical_device: "aphorisme d'ouverture + attaque directe",
      power_score: 10,
      chapter_idx: 1,
      highlight_words: ["too slow", "lose", "people like me"],
    },
    {
      text: "By the time you were done reading the book, the moves have been made.",
      context: "Attaque contre la lenteur intellectuelle livresque",
      tags: ["speed", "anti-reading", "action"],
      rhetorical_device: "métaphore d'échecs",
      power_score: 9,
      chapter_idx: 1,
      highlight_words: ["book", "moves have been made"],
    },
    {
      text: "It's 100% accountability with no luck. That's what's so important about learning chess.",
      context: "Justification du chess comme modèle de vie",
      tags: ["accountability", "chess", "responsabilité"],
      rhetorical_device: "analogie fondatrice",
      power_score: 9,
      chapter_idx: 1,
      highlight_words: ["100% accountability", "no luck"],
    },
    {
      text: "You need to as a man adopt the mindset that absolutely everything that happens to you is completely and utterly your fault, whether it's good or bad.",
      context: "Formulation du cadre 100 % accountability",
      tags: ["accountability", "masculinité", "mindset"],
      rhetorical_device: "impératif catégorique",
      power_score: 10,
      chapter_idx: 1,
      highlight_words: ["everything", "completely and utterly", "your fault"],
    },
    {
      text: "This is my fault. All of this is me. I got here. It's my fault.",
      context: "Réaction face aux attaques Matrix (banques fermées, ex appelées, ban)",
      tags: ["accountability", "matrix", "auto-biographique"],
      rhetorical_device: "anaphore + auto-preuve",
      power_score: 9,
      chapter_idx: 2,
      highlight_words: ["my fault", "I got here"],
    },
    {
      text: "That was unfair. It was orchestrated. The NGOs worked against me. Cuz that is not helpful.",
      context: "Rejet du cadre victimaire — non par déni mais pour le levier",
      tags: ["accountability", "reframe", "stratégie"],
      rhetorical_device: "prosopopée du perdant + retournement",
      power_score: 8,
      chapter_idx: 2,
      highlight_words: ["unfair", "not helpful"],
    },
    {
      text: "If you let life come to you, you're going to be living inside of a matrix.",
      context: "Conclusion de l'analogie Forrest Gump feather",
      tags: ["accountability", "matrix", "agency"],
      rhetorical_device: "métaphore culturelle + conditionnel",
      power_score: 9,
      chapter_idx: 3,
      highlight_words: ["let life come to you", "matrix"],
    },
    {
      text: "Forrest is the feather and life has just pushed him all over.",
      context: "Décodage de la scène d'ouverture de Forrest Gump",
      tags: ["analogy", "agency", "modèle-mental"],
      rhetorical_device: "analogie mythique",
      power_score: 9,
      chapter_idx: 3,
      highlight_words: ["Forrest", "feather", "pushed"],
    },
    {
      text: "You can't let life come to you. You have to come to life.",
      context: "Retournement actif du principe",
      tags: ["agency", "action", "reframe"],
      rhetorical_device: "chiasme rhétorique",
      power_score: 9,
      chapter_idx: 3,
      highlight_words: ["come to life"],
    },
    {
      text: "I'm not subject to circumstance. Tate arrives and circumstances change.",
      context: "Culminant du principe 100 % accountability",
      tags: ["accountability", "agency", "identité"],
      rhetorical_device: "auto-désignation à la 3e personne + inversion",
      power_score: 10,
      chapter_idx: 6,
      highlight_words: ["not subject", "Tate arrives", "circumstances change"],
    },
    {
      text: "Why do you want me to believe this? Do you want me to believe this because it's good for me or is it because it's good for you?",
      context: "Test universel de toute croyance imposée",
      tags: ["matrix", "épistémologie", "cui-bono"],
      rhetorical_device: "question rhétorique en cascade",
      power_score: 9,
      chapter_idx: 4,
      highlight_words: ["good for me", "good for you"],
    },
    {
      text: "All of it is programming. All of it is a lie.",
      context: "Diagnostic global des messages culturels dominants",
      tags: ["matrix", "programming", "conspirationnisme"],
      rhetorical_device: "anaphore + affirmation absolue",
      power_score: 7,
      chapter_idx: 4,
      highlight_words: ["programming", "lie"],
    },
    // Purpose & masculinity
    {
      text: "I'm not interested in fun. I don't understand the concept of fun. Fun is for women and children.",
      context: "Rejet catégorique du fun comme valeur masculine",
      tags: ["purpose", "masculinité", "provocation"],
      rhetorical_device: "gradation + insulte de camp",
      power_score: 9,
      chapter_idx: 5,
      highlight_words: ["Fun is for women and children"],
    },
    {
      text: "I think that the entire world was built by this God-given drive to conquer. And to conquer doesn't always mean dominate others. You can conquer the sky by building a skyscraper.",
      context: "Réhabilitation de la conquête comme construction",
      tags: ["purpose", "conquer", "création"],
      rhetorical_device: "reframe + gradation d'exemples concrets",
      power_score: 8,
      chapter_idx: 5,
      highlight_words: ["God-given drive", "conquer", "skyscraper"],
    },
    {
      text: "You know why I love being around you? I don't have to think.",
      context: "Ce que Tate rapporte que les femmes lui disent",
      tags: ["féminité", "compétence", "cadre-relationnel"],
      rhetorical_device: "témoignage rapporté",
      power_score: 7,
      chapter_idx: 5,
      highlight_words: ["don't have to think"],
    },
    {
      text: "The jet's just on the runway and we just land and I'm in this beautiful place and I don't even know where I am and I get to just turn my brain off.",
      context: "Ce que veut la femme selon Tate : décharge de la pensée logistique",
      tags: ["féminité", "compétence", "logistique"],
      rhetorical_device: "énumération narrative",
      power_score: 6,
      chapter_idx: 5,
      highlight_words: ["turn my brain off"],
    },
    {
      text: "The world has never given a fuck about sad men.",
      context: "Attaque contre la posture victimaire masculine",
      tags: ["masculinité", "harshness", "dépression"],
      rhetorical_device: "vulgarisme calibré + absolutisme",
      power_score: 9,
      chapter_idx: 5,
      highlight_words: ["never given a fuck", "sad men"],
    },
    {
      text: "I know that my sadness, my depression will be temporary because I will never stay a loser. It's against my creed.",
      context: "Auto-portrait comme antithèse du perdant",
      tags: ["mindset", "identité", "stoïcisme"],
      rhetorical_device: "auto-affirmation identitaire",
      power_score: 8,
      chapter_idx: 5,
      highlight_words: ["never stay a loser", "against my creed"],
    },
    {
      text: "Ignorant people can to a degree be happier in certain lives than others. But that all changes when times get hard.",
      context: "Concession nuancée sur le bonheur des ignorants",
      tags: ["bonheur", "ignorance", "nuance"],
      rhetorical_device: "concession + retournement conditionnel",
      power_score: 8,
      chapter_idx: 6,
      highlight_words: ["ignorant", "happier", "times get hard"],
    },
    {
      text: "Your happiness as a man comes from feeling respected over feeling loved.",
      context: "Théorie du bonheur masculin",
      tags: ["masculinité", "respect", "amour"],
      rhetorical_device: "aphorisme structurant",
      power_score: 9,
      chapter_idx: 9,
      highlight_words: ["respected", "loved"],
    },
    {
      text: "Being a good man and being good at being a man are two different things.",
      context: "Distinction Peterson-esque entre vertu éthique et compétence virile",
      tags: ["masculinité", "éthique", "compétence"],
      rhetorical_device: "distinction sémantique",
      power_score: 8,
      chapter_idx: 9,
      highlight_words: ["good man", "good at being a man"],
    },
    // Speed
    {
      text: "I made a song in 2 and 1/2 hours.",
      context: "Anecdote emblème de la doctrine speed",
      tags: ["speed", "action", "preuve"],
      rhetorical_device: "anecdote-preuve minimale",
      power_score: 8,
      chapter_idx: 10,
      highlight_words: ["2 and 1/2 hours"],
    },
    {
      text: "Speed works. Just do it all at once.",
      context: "Formulation loi de la doctrine",
      tags: ["speed", "loi", "impératif"],
      rhetorical_device: "impératif d'action + simplification",
      power_score: 8,
      chapter_idx: 10,
      highlight_words: ["Speed works", "all at once"],
    },
    {
      text: "I'll be reading what I need to read and on the phone and playing chess at the same time. Otherwise, my brain's not full.",
      context: "Auto-portrait de la saturation cognitive comme état par défaut",
      tags: ["speed", "multitasking", "identité"],
      rhetorical_device: "auto-preuve par intensité",
      power_score: 7,
      chapter_idx: 10,
      highlight_words: ["brain's not full"],
    },
    // Money
    {
      text: "Get up off your ass and work first.",
      context: "Attaque contre la demande précoce de revenus passifs",
      tags: ["money", "action", "paresse"],
      rhetorical_device: "impératif vulgaire + priorisation",
      power_score: 9,
      chapter_idx: 11,
      highlight_words: ["Get up off your ass", "work first"],
    },
    {
      text: "Nobody's afraid of saying yes to commission only.",
      context: "Test de la vraie foi entrepreneuriale",
      tags: ["money", "test", "commission"],
      rhetorical_device: "critère opérationnel",
      power_score: 8,
      chapter_idx: 11,
      highlight_words: ["commission only"],
    },
    {
      text: "Business is other people's money.",
      context: "Modèle minimaliste du business, cité d'un pimp",
      tags: ["money", "business", "définition"],
      rhetorical_device: "aphorisme réducteur",
      power_score: 9,
      chapter_idx: 11,
      highlight_words: ["other people's money"],
    },
    {
      text: "Every time I sit in a coffee shop, I think about how I could outcompete them.",
      context: "Frame mental permanent : décoder chaque commerce",
      tags: ["money", "business-thinking", "idéation"],
      rhetorical_device: "auto-exemplification",
      power_score: 8,
      chapter_idx: 11,
      highlight_words: ["coffee shop", "outcompete"],
    },
    {
      text: "I spent 3.2 million dollars of Ferraris. Should I have done that? Well, yeah, I can.",
      context: "Preuve du niveau où l'argent devient irréel",
      tags: ["money", "wealth", "seuil"],
      rhetorical_device: "provocation + auto-justification",
      power_score: 8,
      chapter_idx: 11,
      highlight_words: ["3.2 million", "yeah, I can"],
    },
    {
      text: "I don't have a clue how much money I have.",
      context: "Position paradoxale : le vrai riche ne compte plus",
      tags: ["money", "wealth", "détachement"],
      rhetorical_device: "aveu-preuve",
      power_score: 8,
      chapter_idx: 11,
      highlight_words: ["don't have a clue"],
    },
    {
      text: "My attitude to money is relatively unhealthy. I have no respect for it.",
      context: "Diagnostic auto-administré du détachement financier",
      tags: ["money", "détachement", "psychologie"],
      rhetorical_device: "aveu conscient + provocation",
      power_score: 8,
      chapter_idx: 11,
      highlight_words: ["no respect for it"],
    },
    {
      text: "The asset owners are always going to get richer.",
      context: "Loi anti-redistribution",
      tags: ["money", "asset", "économie"],
      rhetorical_device: "loi générale",
      power_score: 8,
      chapter_idx: 11,
      highlight_words: ["asset owners", "richer"],
    },
    {
      text: "Let's say they gave every person in the UK a thousand pounds. A lot of that money goes to one guy, Jeff Bezos.",
      context: "Preuve concrète du wealth transfer",
      tags: ["money", "redistribution", "économie"],
      rhetorical_device: "expérience de pensée + exemple nommé",
      power_score: 8,
      chapter_idx: 11,
      highlight_words: ["thousand pounds", "Jeff Bezos"],
    },
    {
      text: "I'm not buying rich, I'm buying free. And you're only free with power.",
      context: "Reformulation de la finalité de l'argent",
      tags: ["money", "freedom", "power"],
      rhetorical_device: "chiasme + escalade sémantique",
      power_score: 9,
      chapter_idx: 11,
      highlight_words: ["buying free", "power"],
    },
    {
      text: "By the time I saw Dan in a four-hour whirlwind, you spent 400 grand.",
      context: "Anecdote Bilzerian : le coût de la sécurité personnelle premium",
      tags: ["money", "wealth", "sécurité"],
      rhetorical_device: "chiffre choc + auto-anecdote",
      power_score: 7,
      chapter_idx: 11,
      highlight_words: ["400 grand"],
    },
    // Network
    {
      text: "You are the sum of the five people you spend the most time with.",
      context: "Loi fondamentale du network",
      tags: ["network", "loi", "environnement"],
      rhetorical_device: "aphorisme structurant",
      power_score: 9,
      chapter_idx: 7,
      highlight_words: ["sum", "five people"],
    },
    {
      text: "You will always lose against people like me and my network.",
      context: "Attaque contre l'isolé",
      tags: ["network", "provocation", "hiérarchie"],
      rhetorical_device: "attaque directe + auto-inscription",
      power_score: 9,
      chapter_idx: 7,
      highlight_words: ["always lose", "network"],
    },
    {
      text: "I wanted a network of genuine predators.",
      context: "Genèse du War Room",
      tags: ["network", "predator", "war-room"],
      rhetorical_device: "auto-genèse",
      power_score: 8,
      chapter_idx: 7,
      highlight_words: ["genuine predators"],
    },
    {
      text: "We don't talk about Rihanna, football, Love Island. We only talk about money.",
      context: "Filtre des conversations comme prédicteur de vie",
      tags: ["network", "conversation", "focus"],
      rhetorical_device: "contraste énumératif",
      power_score: 8,
      chapter_idx: 7,
      highlight_words: ["only talk about money"],
    },
    // Confidence & competence
    {
      text: "Confidence comes from competence.",
      context: "Loi opérationnelle du développement personnel",
      tags: ["confidence", "competence", "loi"],
      rhetorical_device: "aphorisme lapidaire",
      power_score: 9,
      chapter_idx: 13,
      highlight_words: ["Confidence", "competence"],
    },
    {
      text: "The reason I'm confident is because I'm good at everything.",
      context: "Auto-fondement de la confidence Tate",
      tags: ["confidence", "competence", "auto-preuve"],
      rhetorical_device: "circularité assumée",
      power_score: 8,
      chapter_idx: 13,
      highlight_words: ["good at everything"],
    },
    {
      text: "Most people don't deserve to be proud of themselves.",
      context: "Attaque contre le self-help générique",
      tags: ["confidence", "harshness", "vérité"],
      rhetorical_device: "affirmation choquante",
      power_score: 9,
      chapter_idx: 13,
      highlight_words: ["don't deserve", "proud"],
    },
    {
      text: "I've created my reality to the point where I don't do anything I'm not good at.",
      context: "Résultat final de la logique competence-first",
      tags: ["confidence", "reality", "compétence"],
      rhetorical_device: "auto-portrait final",
      power_score: 8,
      chapter_idx: 13,
      highlight_words: ["created my reality", "not good at"],
    },
    // Trauma & belief
    {
      text: "Bad things happened to Batman. They killed his parents. That's why he's Batman.",
      context: "Théodicée mythique de la douleur",
      tags: ["trauma", "batman", "mythe"],
      rhetorical_device: "analogie mythique + circularité narrative",
      power_score: 10,
      chapter_idx: 14,
      highlight_words: ["Batman", "killed his parents"],
    },
    {
      text: "The best things ever happened to me are the worst things ever happened to me.",
      context: "Formule reframing du trauma",
      tags: ["trauma", "reframe", "paradoxe"],
      rhetorical_device: "paradoxe + inversion sémantique",
      power_score: 10,
      chapter_idx: 14,
      highlight_words: ["best things", "worst things"],
    },
    {
      text: "If none of this happened to you, when something else bad happens to you later, you wouldn't be able to deal with it.",
      context: "Justification prospective du trauma passé",
      tags: ["trauma", "resilience", "future-proofing"],
      rhetorical_device: "conditionnel projectif",
      power_score: 8,
      chapter_idx: 14,
      highlight_words: ["deal with it"],
    },
    {
      text: "You must believe. You must believe in yourselves.",
      context: "Anaphore religieuse — la croyance comme condition",
      tags: ["belief", "self", "religion"],
      rhetorical_device: "anaphore religieuse",
      power_score: 7,
      chapter_idx: 13,
      highlight_words: ["believe"],
    },
    {
      text: "Everyone said a 4-minute mile was impossible. Then one guy did it and 10 people did it in like 3 weeks.",
      context: "Preuve historique de la barrière mentale",
      tags: ["belief", "plafond", "preuve"],
      rhetorical_device: "anecdote historique + escalade",
      power_score: 9,
      chapter_idx: 13,
      highlight_words: ["4-minute mile", "impossible", "10 people"],
    },
    // Stoicism & attention
    {
      text: "I am the same base level of happy regardless.",
      context: "Base line émotionnelle stable comme socle stoïque",
      tags: ["stoïcisme", "émotion", "stabilité"],
      rhetorical_device: "auto-portrait affectif",
      power_score: 7,
      chapter_idx: 14,
      highlight_words: ["same base level"],
    },
    {
      text: "Inside of every single man, we're born with a fire inside of us that we do not control can destroy ourselves and other people.",
      context: "Anthropologie tragique — justification du stoïcisme",
      tags: ["stoïcisme", "anthropologie", "violence"],
      rhetorical_device: "diagnostic universel",
      power_score: 8,
      chapter_idx: 14,
      highlight_words: ["fire inside", "destroy"],
    },
    {
      text: "Telling men to not be stoic is going to create violent young men.",
      context: "Retournement civique du stoïcisme",
      tags: ["stoïcisme", "civique", "violence"],
      rhetorical_device: "retournement de l'accusation",
      power_score: 9,
      chapter_idx: 14,
      highlight_words: ["not be stoic", "violent young men"],
    },
    {
      text: "The most valuable thing that exists is attention.",
      context: "Diagnostic économique de l'ère TikTok",
      tags: ["attention", "économie", "monnaie"],
      rhetorical_device: "affirmation absolue",
      power_score: 9,
      chapter_idx: 12,
      highlight_words: ["attention"],
    },
    {
      text: "Have you ever watched someone on TikTok? Maybe a third of a second?",
      context: "Constat empirique du seuil d'attention",
      tags: ["attention", "tiktok", "seuil"],
      rhetorical_device: "question rhétorique + chiffre",
      power_score: 8,
      chapter_idx: 12,
      highlight_words: ["third of a second"],
    },
    {
      text: "Your ability to speak freely is directly correlated to your insignificance.",
      context: "Point contre-intuitif sur la free speech",
      tags: ["free-speech", "influence", "paradoxe"],
      rhetorical_device: "corrélation inversée",
      power_score: 9,
      chapter_idx: 14,
      highlight_words: ["speak freely", "insignificance"],
    },
    // Value exchange
    {
      text: "Life is a value exchange.",
      context: "Loi générale des relations",
      tags: ["value-exchange", "loi", "relations"],
      rhetorical_device: "aphorisme structurant",
      power_score: 8,
      chapter_idx: 7,
      highlight_words: ["value exchange"],
    },
    {
      text: "Every friendship, every relationship, every business, there has to be an exchange of value.",
      context: "Extension du principe à tous les liens",
      tags: ["value-exchange", "extension", "loi"],
      rhetorical_device: "anaphore + généralisation",
      power_score: 8,
      chapter_idx: 7,
      highlight_words: ["exchange of value"],
    },
    {
      text: "Reading a book is a reward without any risk.",
      context: "Attaque contre l'apprentissage livresque",
      tags: ["reading", "risk", "attaque"],
      rhetorical_device: "reframe négatif d'une vertu",
      power_score: 8,
      chapter_idx: 1,
      highlight_words: ["reward without any risk"],
    },
    {
      text: "How much you want is how much you're prepared to sacrifice.",
      context: "Loi de l'ambition",
      tags: ["sacrifice", "ambition", "loi"],
      rhetorical_device: "équation symétrique",
      power_score: 8,
      chapter_idx: 5,
      highlight_words: ["sacrifice"],
    },
    {
      text: "I could never be broke ever again.",
      context: "Auto-affirmation post-network — pas cash mais capital-relations",
      tags: ["money", "network", "sécurité"],
      rhetorical_device: "auto-affirmation irréversible",
      power_score: 8,
      chapter_idx: 7,
      highlight_words: ["never be broke"],
    },
    {
      text: "I don't want to hear it. Choose your character and build it.",
      context: "Rejet des excuses identitaires",
      tags: ["identité", "action", "choice"],
      rhetorical_device: "impératif ludique (video-game frame)",
      power_score: 8,
      chapter_idx: 5,
      highlight_words: ["Choose your character", "build it"],
    },
    {
      text: "I don't give a solitary fuck if you want to stay at the bottom.",
      context: "Refus de sympathie envers les non-battants",
      tags: ["harshness", "sympathy", "refus"],
      rhetorical_device: "vulgarisme calibré + désengagement",
      power_score: 8,
      chapter_idx: 5,
      highlight_words: ["stay at the bottom"],
    },
    {
      text: "I want them growing up in deep Russia, in the mountains with goats, running in the snow barefoot.",
      context: "Doctrine d'éducation dure appliquée à ses enfants",
      tags: ["éducation", "trauma", "enfants"],
      rhetorical_device: "vision romantique + concret",
      power_score: 7,
      chapter_idx: 8,
      highlight_words: ["deep Russia", "snow barefoot"],
    },
    {
      text: "I'm a vessel of God and I'm happy.",
      context: "Auto-portrait spirituel — clôture serein",
      tags: ["religion", "identité", "sérénité"],
      rhetorical_device: "auto-designation sacrée",
      power_score: 7,
      chapter_idx: 14,
      highlight_words: ["vessel of God"],
    },
  ],

  // ============================================================
  // 5. ARGUMENTATION KIT
  // ============================================================
  argumentation_kit: {
    how_to_defend: [
      {
        challenge: "« Le 100 % accountability, c'est victim-blaming. Une femme violée, c'est sa faute ? »",
        response: "Distinguer deux niveaux : moralement, non — stratégiquement, la question 'où est mon levier ?' est toujours la seule utile.",
        technique: "Distinction niveau moral vs niveau stratégique — reframe outil",
        example_response_text: "Le 100 % accountability n'est pas un jugement moral, c'est un outil de levier. Personne ne dit qu'une victime est coupable. On dit : dans ma vie à moi, si je cherche mes leviers d'action même dans le pire scénario, je récupère ma puissance. C'est une posture personnelle, pas un verdict extérieur.",
      },
      {
        challenge: "« Tu prêches la vitesse mais ton morceau musical a fait des vues grâce à ta célébrité, pas à sa qualité. »",
        response: "Concéder le point sur ce cas précis, mais retourner : c'est *parce que* j'ai construit vite dès le début que j'ai eu l'audience.",
        technique: "Concession + retournement causal",
        example_response_text: "Correct — la track a marché grâce à mon audience. Mais l'audience elle-même, je l'ai construite en publiant vite, mal, souvent, quand personne ne me connaissait. La speed a été le moteur du départ, pas juste l'accélérateur d'arrivée. La qualité vient de la répétition, pas de l'attente.",
      },
      {
        challenge: "« Ton attaque contre les livres est incohérente : tu cites Nietzsche, l'histoire de Rome, la Bible. Tu lis. »",
        response: "Distinguer lecture stratégique (pour appliquer) vs lecture-refuge (pour éviter d'agir).",
        technique: "Distinction sémantique — sauver la thèse en précisant",
        example_response_text: "Je ne dis pas 'ne lis pas' — je dis 'ne fais pas de la lecture ton alibi contre l'action'. Je lis 30 min pour armer une décision, pas 8h pour éviter une décision. Le livre comme récompense sans risque est le piège. Le livre comme munition pour action est un actif.",
      },
      {
        challenge: "« Ta doctrine du network est élitiste : tout le monde ne peut pas être dans un War Room. »",
        response: "Réponse : tout le monde peut passer 30 min moins avec ses relations médiocres et 30 min plus avec la personne la plus ambitieuse qu'il connaît. Le principe est gradient, pas binaire.",
        technique: "Redimensionnement du principe — l'application est graduelle",
        example_response_text: "Le War Room est un cas extrême. Le principe est gradient : audit tes 5 relations, coupe la plus toxique, remplace-la par la plus ambitieuse. Fais ça 6 fois par an. En 3 ans, ton cercle est méconnaissable. Pas besoin d'appartenir à un club — juste d'appliquer le tri.",
      },
      {
        challenge: "« Dire aux hommes que la dépression n'existe pas va pousser des dépressifs au suicide. »",
        response: "Distinguer feeling depressed (état passager reframable) vs having clinical depression (à traiter médicalement). Ne pas confondre les deux.",
        technique: "Reframe médical vs conversationnel",
        example_response_text: "Je ne parle pas de la dépression clinique — celle-là, va voir un médecin. Je parle de la 'dépression paresseuse' qu'on s'invente pour excuser l'inaction. La confondre avec la vraie dépression est un service à personne. La différence : la clinique, tu ne peux pas la 'outrun'. La paresseuse, si.",
      },
      {
        challenge: "« Le 'Fun is for women and children', c'est misogyne et infantilisant. »",
        response: "Reformuler en distinguant deux modes : mode récepteur d'expérience (fun) vs mode créateur d'expérience (purpose). Pas de hiérarchie de valeur — hiérarchie de mode.",
        technique: "Reformulation neutre du binaire genré",
        example_response_text: "La formulation est provocante, je l'accorde. Le fond est : il y a deux modes de rapport à l'expérience — recevoir (fun) et créer (purpose). Les enfants et les femmes ont plus de latitude sociale pour recevoir. Un homme adulte structuré autour du 'recevoir' est perdu. Ce n'est pas un jugement sur les femmes ; c'est un diagnostic sur l'homme.",
      },
      {
        challenge: "« Tu dis 'confidence vient de competence' mais des athlètes surentraînés sont anxieux. »",
        response: "La competence non reconnue par soi-même ne suffit pas — il faut aussi *croire à sa compétence*. La croyance et la compétence forment un couple.",
        technique: "Ajout d'un facteur — sauver la thèse en la complexifiant",
        example_response_text: "Vrai — competence sans awareness de sa competence produit encore de l'anxiété. Il faut competence + preuve empirique répétée + reconnaissance interne. Mais la confidence 'sans competence' est du théâtre. La vraie question : où est ta preuve empirique la plus récente ?",
      },
      {
        challenge: "« Le stoïcisme émotionnel produit des hommes coupés d'eux-mêmes qui explosent à 50 ans. »",
        response: "Distinguer stoïcisme opératif (décision > émotion sur l'action) vs suppression émotionnelle. Le premier permet la seconde n'est pas ce qui est prêché.",
        technique: "Distinction sur ce qu'on entend par stoïcisme",
        example_response_text: "Le stoïcisme dont je parle n'est pas 'ne ressens rien'. C'est 'ressens tout, mais que l'émotion ne dicte pas l'action'. Un stoïcien pleure aux enterrements, prend la décision juste malgré la colère. La suppression pure, c'est autre chose — et elle explose effectivement à 50 ans. Confondre les deux est une erreur de définition.",
      },
    ],
    how_to_attack: [
      {
        target_claim: "« Le monde ne parle que d'argent dans mon cercle » comme filtre de vie",
        attack: "Ce filtre exclut par construction toute conversation intellectuelle, esthétique, spirituelle. Il produit un monde plat où la seule métrique est le compte en banque.",
        angle: "Éthique + phénoménologique",
      },
      {
        target_claim: "« Reading is a reward without risk »",
        attack: "Aucun apprentissage à haute densité n'est possible sans lecture. Rejeter les livres = revenir à la culture orale. Toutes les compétences de haut niveau de Tate lui-même viennent d'une culture livresque (échecs, histoire, rhétorique).",
        angle: "Empirique + auto-contradiction",
      },
      {
        target_claim: "« I am the circumstance / Tate arrives and circumstances change »",
        attack: "Confond agency personnelle et détermination des circonstances externes. Une grande partie des circonstances (marchés, régimes politiques, santé) est structurellement indépendante de l'agent. La formulation est vraie à l'échelle micro, fausse à l'échelle macro.",
        angle: "Logique + empirique",
      },
      {
        target_claim: "« Elevons les enfants dans les montagnes russes pieds nus »",
        attack: "Les enfants élevés dans une réelle rareté sont statistiquement plus fragiles à l'âge adulte, pas plus forts. La sélection darwinienne n'est pas un plan d'éducation. Sa fille recevra un jet privé, pas une chèvre.",
        angle: "Empirique + auto-contradiction",
      },
      {
        target_claim: "Le success de Tate comme preuve universelle de sa doctrine",
        attack: "Survivor bias structurel : Tate ne voit pas les cimetières. Combien d'hommes ont suivi 'commission only + 18h/j + no reading' et sont morts brisés ou en dépression ? Sa statistique intime est incomplète.",
        angle: "Épistémologique — biais des survivants",
      },
      {
        target_claim: "« Weak men are the most dangerous »",
        attack: "Historiquement, les pires atrocités (Auschwitz, goulags) ont été perpétrées par des bureaucrates stoïques, pas par des hommes émotifs. Le stoïcisme sans éthique = machine à obéir aux ordres. La force émotionnelle ≠ éthique.",
        angle: "Historique + éthique",
      },
    ],
    how_to_rephrase: [
      {
        original: "You're too slow and you are going to lose against people like me.",
        softer: "La vitesse d'exécution est aujourd'hui plus décisive que l'excellence retardée — ceux qui livrent maintenant prennent les positions.",
        harder: "T'es trop lent, mon pote. Le temps que tu réfléchisses, moi j'ai encaissé et je suis passé au suivant.",
        academic: "Dans une économie de l'information à haute vélocité, l'avantage compétitif se déplace de la maîtrise théorique vers l'itération rapide, ce que Boyd (OODA loop) et les théoriciens du lean startup ont formalisé.",
      },
      {
        original: "Fun is for women and children.",
        softer: "Le mode 'divertissement passif' n'organise pas une vie masculine à haute performance ; il faut lui préférer le mode 'purpose actif'.",
        harder: "Le fun c'est pour les meufs et les gosses. Toi, adulte, tu construis ou tu es figurant.",
        academic: "Aristote distingue la vie de plaisir (bios apolaustikos) de la vie contemplative et politique. Le premier mode, structurellement passif, ne permet pas l'accomplissement de l'eudaimonia active propre à l'homme adulte.",
      },
      {
        original: "Business is other people's money.",
        softer: "Toute activité économique consiste à déclencher un transfert de valeur volontaire depuis d'autres portefeuilles vers le vôtre.",
        harder: "Le business c'est du pognon des autres qui atterrit chez toi. Ferme le manuel, ouvre un stand.",
        academic: "L'entreprise est une organisation dont la fonction est la captation et la réallocation de flux de capitaux en échange de valeur perçue, selon la théorie des coûts de transaction (Coase, Williamson).",
      },
      {
        original: "Everything that happens to you is completely and utterly your fault.",
        softer: "Adopter une posture de responsabilité totale — même quand elle est factuellement discutable — est le seul moyen de récupérer un levier d'action.",
        harder: "Ta merde, c'est toi. Point. Pas la société, pas ton daron, pas la chance. Toi.",
        academic: "L'internal locus of control (Rotter, 1966) est corrélé à des indicateurs de résilience et de performance ; l'auteur en propose une version radicale comme technique de leviérage stratégique.",
      },
      {
        original: "Confidence comes from competence.",
        softer: "La confiance stable et non-performative est une conséquence de la compétence prouvée, pas une cause préalable.",
        harder: "T'as confiance parce que t'es bon. Sois bon d'abord, ta confiance suivra toute seule.",
        academic: "La self-efficacy (Bandura, 1977) se développe par mastery experiences ; les techniques d'affirmation cognitive isolées ne produisent pas d'effet durable sans ancrage empirique.",
      },
      {
        original: "The best things ever happened to me are the worst things ever happened to me.",
        softer: "Les périodes les plus difficiles produisent, à condition d'être digérées, les fondations les plus solides de la personnalité et de la compétence.",
        harder: "Ce qui m'a défoncé, c'est ce qui m'a fait. Sans ces coups, je serais un mou comme toi.",
        academic: "La croissance post-traumatique (Tedeschi & Calhoun) documente comment l'adversité, intégrée narrativement, produit des gains en résilience, sens et compétence.",
      },
      {
        original: "Get up off your ass and work first.",
        softer: "L'ordre optimal est : accumulation par revenus actifs saturés → optimisation par systèmes passifs — jamais l'inverse.",
        harder: "Bouge ton cul. Bosse. La chill room passive tu la construiras quand t'auras rien à foutre.",
        academic: "L'accumulation initiale de capital requiert un investissement en temps direct dont la passivation n'est possible qu'après atteinte d'un seuil de flux (marginalisme et théorie de l'investissement).",
      },
      {
        original: "You are the sum of the five people you spend the most time with.",
        softer: "Ton environnement social proche détermine, par imitation inconsciente et par flux d'informations, la trajectoire de tes décisions.",
        harder: "T'es tes 5 potes. Regarde-les : c'est toi dans 3 ans. Content ?",
        academic: "Les théories de la contagion sociale (Christakis & Fowler, 2007) documentent la propagation des comportements dans les réseaux à trois degrés de séparation.",
      },
    ],
    if_asked: [
      {
        question: "Si on t'accuse d'être un gourou toxique, comment tu réponds ?",
        best_response: "Je réponds par le fond, pas par le procès d'intention. Prends une thèse précise, on la discute. 'Toxique' est une étiquette d'évitement — elle n'est pas un argument. Le mot qui compte n'est pas 'toxique' mais 'vrai ou faux'.",
        followup_moves: [
          "Demander la thèse exacte contestée",
          "Offrir la version steelman de sa propre position pour montrer qu'on la comprend",
          "Ramener sur : est-ce que ça marche empiriquement ?",
        ],
      },
      {
        question: "Comment défendre l'idée de 100 % accountability sans tomber dans le victim-blaming ?",
        best_response: "En précisant : c'est une posture personnelle de leviérage, pas un verdict extérieur. Personne ne juge la victime. La victime, elle, peut choisir cette posture *pour elle-même* pour récupérer de la puissance. C'est une auto-adressée, pas une hétéro-adressée.",
        followup_moves: [
          "Distinguer moral vs stratégique",
          "Citer Frankl : entre stimulus et réponse, il y a un espace",
          "Insister : c'est un outil, pas un jugement",
        ],
      },
      {
        question: "Est-ce que la doctrine de la vitesse fonctionne quand on part de zéro ?",
        best_response: "Oui, mais différemment. Sans audience, la speed te sert à *itérer* : 50 versions faibles t'apprennent plus que 1 version 'parfaite'. Le morceau de Tate à 2h a marché grâce à son audience, mais l'audience elle-même a été bâtie par 10 ans de speed avant le succès.",
        followup_moves: [
          "Concéder l'objection sur ce cas précis",
          "Retourner : la speed est le moteur du départ, pas seulement l'accélérateur d'arrivée",
          "Donner un exemple : 100 vidéos ratées > 1 vidéo parfaite",
        ],
      },
      {
        question: "Comment concilier 'fun is for women and children' avec le fait que le play est essentiel au bonheur ?",
        best_response: "Reformulons : Tate distingue deux modes — recevoir de l'expérience (fun passif) et créer de l'expérience (jeu actif, sport, conquête). Un homme adulte structuré autour du 'recevoir' est perdu. Un homme qui joue en créant — sport, business, art — vit un 'fun' que Tate n'appellerait pas fun mais qui l'est.",
        followup_moves: [
          "Distinguer passif vs actif",
          "Rappeler que Tate boxe, dispute, conquiert — c'est son fun",
          "Recadrer 'fun' comme mot ambigu",
        ],
      },
      {
        question: "Comment répondre à quelqu'un qui dit 'l'argent ne fait pas le bonheur' ?",
        best_response: "L'argent ne fait pas le bonheur, mais il achète l'espace où le bonheur devient possible : temps, sécurité, options, absence de peur. Nier ça, c'est confondre la métaphysique et l'infrastructure. Sans infrastructure, la métaphysique s'écroule.",
        followup_moves: [
          "Distinguer bonheur direct vs infrastructure du bonheur",
          "Citer l'étude Kahneman (jusqu'à ~75k$/an, l'argent améliore mesurablement)",
          "Retourner : 'la pauvreté fait le malheur' est empiriquement vérifié",
        ],
      },
      {
        question: "Que faire concrètement pour appliquer 'confidence ← competence' cette semaine ?",
        best_response: "Trois étapes : (1) Choisis UN domaine mesurable où tu peux tester ta compétence dans les 7 jours. (2) Passe 3 heures intenses à te confronter à un standard extérieur (client, professeur, arbitre). (3) Note écart entre auto-perception et retour extérieur. Ce petit cycle est le prototype de la confidence durable.",
        followup_moves: [
          "Insister sur le mesurable",
          "Rappeler : pas de flatteur — un standard dur",
          "Répéter le cycle 12 fois pour l'ancrer",
        ],
      },
      {
        question: "Comment gérer un network audit sans détruire ses vieilles amitiés ?",
        best_response: "Le network audit n'est pas 'couper les amis'. C'est 'réallouer le temps'. Tu peux garder 30 ans d'amitié à basse fréquence (1 fois par mois) tout en construisant activement une couche haute fréquence avec des gens en montée. Le lien reste, la vitesse aussi.",
        followup_moves: [
          "Distinguer coupure vs réallocation",
          "Prévoir une couche 'basse fréquence maintenue'",
          "Nommer les personnes qui doivent monter en fréquence",
        ],
      },
      {
        question: "Est-ce que la doctrine du trauma comme building block est valable pour toute forme de trauma ?",
        best_response: "Non. Les traumas complexes non-traités (abus prolongé, PTSD) ne deviennent pas des atouts par simple reframing — ils exigent un travail thérapeutique. Le reframing marche sur les douleurs digérées, pas sur les blessures ouvertes. Confondre les deux est dangereux.",
        followup_moves: [
          "Distinguer douleur digérée vs blessure ouverte",
          "Recommander travail thérapeutique en parallèle",
          "Insister : le reframing est un outil final, pas un substitut au soin",
        ],
      },
      {
        question: "Comment répondre à quelqu'un qui dit 'ton attention economy pousse à la manipulation ' ?",
        best_response: "Vrai. L'attention economy récompense structurellement le sensationnel. La question n'est pas 'faut-il jouer le jeu ?', c'est 'comment le jouer avec intégrité ?'. Refuser le jeu = disparaître. Le jouer sans éthique = devenir bruit. Le jouer avec éthique = capter attention pour transmettre substance.",
        followup_moves: [
          "Concéder le problème structurel",
          "Retourner sur la question de la seule stratégie viable",
          "Proposer : hook fort + substance derrière",
        ],
      },
      {
        question: "Comment défendre 'le stress a un effet placebo' sans nier la biologie ?",
        best_response: "L'étude citée (Kelly McGonigal / Alia Crum) ne dit pas 'le stress n'existe pas'. Elle dit : à cortisol égal, le récit intérieur module la réponse physiologique et la mortalité. La biologie reste vraie ; l'interprétation cognitive intervient dans la boucle. Reframing n'est pas déni.",
        followup_moves: [
          "Nommer l'étude précise (Crum et al., 2013)",
          "Distinguer biologie brute vs boucle cognition-physiologie",
          "Insister : reframing ≠ nier le stimulus",
        ],
      },
    ],
  },

  // ============================================================
  // 6. FALLACIES & NUANCES
  // ============================================================
  fallacies: [
    {
      original_claim: "Everything that happens to you is completely and utterly your fault, whether it's good or bad.",
      fallacy_type: "fausse dichotomie + surattribution causale",
      why_fallacious: "Nie l'existence de facteurs structurels (marchés, régimes politiques, hérédité, chance) indépendants de l'agent. Fait passer une posture stratégique pour une vérité ontologique.",
      steelman: "En tant qu'outil de leviérage psychologique, la posture 100 % accountability est extrêmement efficace : elle libère du ressentiment paralysant et redirige l'énergie vers l'action. Frankl, Stockdale, les stoïciens antiques y ont vu la seule voie viable en captivité.",
      nuance: "Vrai comme technique de leviérage individuel. Faux comme description factuelle des causalités sociales. Confondre les deux mène à culpabiliser les victimes d'injustices structurelles.",
      counter_argument: "Adopte la posture comme *outil* : dis 'je suis responsable de ma réponse' plutôt que 'je suis responsable de tout ce qui m'arrive'. Cela préserve le levier sans nier la réalité des injustices.",
      severity: "high",
    },
    {
      original_claim: "Reading a book is a reward without any risk.",
      fallacy_type: "faux dilemme + auto-contradiction",
      why_fallacious: "Oppose lecture et action comme si elles étaient exclusives. Tate lui-même a bâti sa culture d'échecs, d'histoire et de rhétorique par la lecture. Il ne pratique pas ce qu'il prêche.",
      steelman: "Il y a une vraie forme d'évasion via la lecture, où on accumule du savoir en simulacre de progression, sans jamais tester dans le réel. La lecture-refuge est un phénomène observable.",
      nuance: "Vrai : la lecture sans application est un simulacre. Faux : la lecture est une des sources majeures de compétence tactique. La bonne question : quel ratio lecture/action ? Pas : faut-il lire ?",
      counter_argument: "La lecture est munition pour l'action. 30 min de lecture précédée de 'quelle décision cela va-t-il informer ?' produit plus qu'1 h d'action non-préparée.",
      severity: "medium",
    },
    {
      original_claim: "You are the sum of the five people you spend the most time with.",
      fallacy_type: "surévaluation d'un déterminisme social",
      why_fallacious: "Formulation aphorisée qui présente une corrélation observée comme une équation stricte. Ignore l'agence individuelle, les influences virtuelles (livres, podcasts, mentors éloignés), et les contre-exemples nombreux.",
      steelman: "L'influence sociale proche est massive et sous-estimée. Christakis & Fowler documentent la contagion à trois degrés de séparation. Le principe pointe vers une variable réelle et souvent négligée.",
      nuance: "Vrai comme heuristique motivationnelle. Faux comme description mécanique. Certains individus rompent avec leur environnement (contre-exemples : self-made scientists, exiles créatifs).",
      counter_argument: "Ton environnement pèse — mais tu peux le composer intentionnellement, y compris avec des mentors virtuels et des livres. La formule est vraie *si tu la rends vraie*.",
      severity: "low",
    },
    {
      original_claim: "The best things ever happened to me are the worst things ever happened to me.",
      fallacy_type: "biais rétrospectif + généralisation abusive",
      why_fallacious: "Rétro-narration cohérente à partir de la position de succès. Ceux qui n'ont pas survécu au 'worst' ne peuvent pas dire le contraire. Survivor bias.",
      steelman: "La croissance post-traumatique (Tedeschi & Calhoun) est un phénomène documenté : les épreuves intégrées produisent des gains en résilience, sens et compétence. Le principe pointe vers un mécanisme réel.",
      nuance: "Vrai pour les traumas digérés dans un contexte porteur. Faux comme loi universelle : beaucoup de traumas non traités restent invalidants ; les statistiques de PTSD, dépression et suicide en témoignent.",
      counter_argument: "Le reframing marche sur les douleurs digérées, pas sur les blessures ouvertes. Sans travail thérapeutique en amont, la formule culpabilise ceux qui n'y arrivent pas.",
      severity: "medium",
    },
    {
      original_claim: "Fun is for women and children.",
      fallacy_type: "essentialisme de genre + faux binaire",
      why_fallacious: "Assigne une activité (le fun) à des catégories (femmes, enfants) sans justification empirique. Crée un binaire moral (fun = féminin/inférieur, purpose = masculin/supérieur) qui ne résiste pas à l'observation.",
      steelman: "L'auteur souligne un phénomène réel : la sur-consommation d'expériences passives (entertainment, scrolling) chez les hommes adultes est corrélée à la stagnation. Le point sous-jacent — 'l'homme adulte doit créer, pas seulement recevoir' — est défendable.",
      nuance: "Le fond (structurer sa vie autour du purpose plutôt que du plaisir passif) est solide. La forme (essentialiser le genre) est une provocation qui affaiblit l'argument et l'expose au rejet légitime.",
      counter_argument: "Reformuler sans essentialisme : distinguer 'mode récepteur' et 'mode créateur' d'expérience. Un homme structuré autour du recevoir est perdu — indépendamment de ce que 'font les femmes'.",
      severity: "medium",
    },
    {
      original_claim: "The reason I'm confident is because I'm good at everything.",
      fallacy_type: "hyperbole + auto-preuve circulaire",
      why_fallacious: "Personne n'est bon à tout. La formulation est une bravade qui invalide sa fonction argumentative : si on ne peut pas être 'bon à tout', ce n'est pas un plan reproductible.",
      steelman: "L'auteur reformule ailleurs : 'I don't do anything I'm not good at' — c'est-à-dire il a curaté son domaine d'action pour n'être visible que sur ses forces. Cela rend la formule cohérente.",
      nuance: "Vrai à l'échelle de sa vie curatée. Faux comme description objective. À reformuler : 'je suis compétent dans tout ce que je choisis de faire publiquement' — beaucoup plus honnête.",
      counter_argument: "La stratégie utile : identifier ton domaine d'excellence, y aller à 100 %, déléguer le reste. Pas : prétendre à l'omnicompétence.",
      severity: "low",
    },
    {
      original_claim: "I want them growing up in deep Russia, in the mountains with goats, running in the snow barefoot.",
      fallacy_type: "romantisation de la pauvreté + généralisation d'un exemple",
      why_fallacious: "Assume que la difficulté physique produit mécaniquement la vertu. Ignore les données empiriques : les enfants élevés dans la pauvreté rurale sont statistiquement plus fragiles à l'âge adulte, pas plus forts.",
      steelman: "Le point sous-jacent — 'ne pas élever ses enfants dans le confort passif absolu' — est défendable. Une part de difficulté intentionnelle (sport dur, responsabilités, travail) est un actif éducatif reconnu.",
      nuance: "Difficulté *choisie* dans un contexte de sécurité affective = actif. Difficulté *subie* dans un contexte de rareté totale = trauma. Confondre les deux est dangereux.",
      counter_argument: "Introduire de la difficulté volontaire (sport, travail, deadlines) dans un contexte de sécurité affective — pas la précarité brute.",
      severity: "medium",
    },
    {
      original_claim: "The weak men are the most dangerous.",
      fallacy_type: "fausse causalité + contre-exemples historiques",
      why_fallacious: "Historiquement, les pires atrocités (Auschwitz, goulags, génocides) ont été perpétrées par des hommes stoïques et disciplinés — bureaucrates, exécutants, soldats — pas par des hommes émotifs.",
      steelman: "Le point sous-jacent — 'les hommes qui n'ont pas de maîtrise émotionnelle produisent de la violence impulsive' — est défendable au niveau individuel (violence conjugale, rixes, crises).",
      nuance: "Vrai à l'échelle individuelle et impulsive. Faux à l'échelle collective et systémique. La force émotionnelle ≠ éthique — Eichmann était stoïque.",
      counter_argument: "Le stoïcisme est un outil neutre. Il peut servir l'obéissance aveugle ou l'éthique. Sans éthique explicite, il est aussi dangereux qu'utile.",
      severity: "high",
    },
    {
      original_claim: "Your ability to speak freely is directly correlated to your insignificance.",
      fallacy_type: "paradoxe séduisant mais surgénéralisé",
      why_fallacious: "Nombreux contre-exemples : figures publiques qui parlent librement sans conséquences (protégées par leur position même). Le principe n'est pas une loi mais une tendance conditionnelle.",
      steelman: "L'observation empirique de fond est vraie : plus tu as d'audience, plus tu as d'ennemis, plus le coût social de la vérité augmente. Le principe pointe vers une dynamique réelle.",
      nuance: "Vrai comme tendance générale. Faux comme loi absolue. Il existe des figures suffisamment puissantes pour se protéger *par* la parole libre (Musk, Rogan à un moment).",
      counter_argument: "La liberté de parole est fonction de : audience × capital politique × valeurs de la plateforme. C'est modulé, pas déterministe.",
      severity: "low",
    },
    {
      original_claim: "Business is other people's money.",
      fallacy_type: "réductionnisme",
      why_fallacious: "Aphorisme séduisant qui capture 30 % du réel : le business est aussi création de valeur, coordination, innovation, création de sens. Le réduire au transfert monétaire est simpliste.",
      steelman: "Comme heuristique de départ pour un débutant, la formule est utile : elle force à penser 'où est mon flux entrant ?' plutôt que 'quel joli produit vais-je inventer ?'. C'est un correctif au piège du créateur.",
      nuance: "Vrai comme test pragmatique de première étape. Faux comme description complète. Un business durable a un flux monétaire ET une proposition de valeur qui la justifie.",
      counter_argument: "Ta thèse : 'business = flux monétaire depuis les autres vers toi via la valeur perçue'. Sans la deuxième clause, c'est de l'extraction, pas du business.",
      severity: "low",
    },
    {
      original_claim: "Free money = wealth transfer aux asset owners (donc pas de redistribution).",
      fallacy_type: "faux dilemme + généralisation abusive",
      why_fallacious: "Sauter de 'la redistribution simple bénéficie aussi aux asset owners' à 'donc toute redistribution est inutile' ignore le fait qu'elle améliore le niveau de vie du bénéficiaire (santé, éducation, mobilité) même si les asset owners bénéficient marginalement plus.",
      steelman: "Le point sous-jacent — 'sans changement structurel, tout stimulus finit dans les mains des grands' — est empiriquement vrai (études sur les stimulus checks Covid).",
      nuance: "Vrai comme critique de la redistribution *non couplée* à d'autres mesures (régulation antitrust, taxation du capital, éducation). Faux comme argument contre la redistribution en général.",
      counter_argument: "Redistribuer + taxer les asset owners + investir dans l'éducation = combinaison. Le problème n'est pas la redistribution, c'est l'absence des autres composants.",
      severity: "medium",
    },
    {
      original_claim: "Ignorant people can be happier — but that all changes when times get hard.",
      fallacy_type: "concession-trap",
      why_fallacious: "Semble ouvert au débat, mais reformule la nuance pour maintenir la thèse : les ignorants perdent 'quand ça devient dur'. Or 'quand ça devient dur' est une clause hyper-large qui peut ne jamais arriver.",
      steelman: "Le point pointe vers une vraie asymétrie de résilience : ceux qui n'ont pas construit d'outils sont vulnérables aux crises. Vrai empiriquement.",
      nuance: "Vrai pour les crises externes (économique, guerre, maladie). Faux comme prédiction universelle : beaucoup de vies 'ignorantes' se terminent paisiblement.",
      counter_argument: "L'asymétrie existe mais son activation est probabiliste. La stratégie 'construire des outils' est bonne, mais pas parce que 'l'ignorance perd toujours' — parce qu'elle perd *en cas de crise*.",
      severity: "low",
    },
    {
      original_claim: "I don't have a clue how much money I have. Money has no value for me.",
      fallacy_type: "signaling + provocation stratégique",
      why_fallacious: "Difficilement vérifiable, et si vrai, contredit sa propre doctrine du 'active income first' qui suppose qu'on compte. Fonction signalétique — 'je suis si riche que je ne compte plus' — plus qu'affirmation littérale.",
      steelman: "Réelle position psychologique post-abondance : quand le capital circule à un certain volume, l'anxiété du compte disparaît. Beaucoup de très riches confirment ce détachement.",
      nuance: "Vrai comme expérience psychologique à haut niveau de wealth. Faux comme conseil applicable au débutant. À qui parle-t-il — au 99 % qui compte, ou au 1 % qui ne compte plus ?",
      counter_argument: "Cette formule est un aveu de position, pas un conseil. Le lecteur au stade actif income doit compter obsessionnellement. Le détachement vient *après*, pas *à la place*.",
      severity: "low",
    },
    {
      original_claim: "You must believe. Belief creates action which creates reality (4-minute mile).",
      fallacy_type: "généralisation d'un mécanisme partiel",
      why_fallacious: "Le 4-minute mile est un cas où la barrière était effectivement mentale — mais nombreuses barrières sont physiques, structurelles, financières. Élargir le mécanisme à 'tout est possible si tu crois' est une erreur d'échelle.",
      steelman: "Le mécanisme réel : les self-fulfilling prophecies existent (études sur l'effet Pygmalion). Croire à un objectif module l'effort, la sélection d'opportunités, et la persistance. Le principe pointe vers un mécanisme documenté.",
      nuance: "Vrai pour les objectifs où l'auto-limitation mentale est le facteur bloquant. Faux pour les objectifs limités par des contraintes physiques/structurelles réelles.",
      counter_argument: "Croire est nécessaire mais pas suffisant. Croire + compétence + circonstances alignées + persistance = résultat. Isoler la croyance est trompeur.",
      severity: "low",
    },
  ],

  // ============================================================
  // 7. STATS & INFOGRAPHICS
  // ============================================================
  stats: [
    {
      number: "0.25s",
      label: "Durée d'attention moyenne pour juger un contenu TikTok",
      source: "Estimation Tate — cohérente avec études YouTube (Wistia) sur les 3 premières secondes",
      context: "Argument-clé de l'attention economy : sans hook immédiat, la valeur ne se monétise pas",
      visual: "count-up",
    },
    {
      number: "$3.2M",
      label: "Dépense en Ferraris de Tate — preuve du seuil d'irréalité de l'argent",
      source: "Auto-déclaration Tate",
      context: "Utilisé pour illustrer qu'au-delà d'un seuil, l'argent devient abstraction",
      visual: "comparison",
    },
    {
      number: "£400k",
      label: "Coût de 4 heures avec Dan Bilzerian (jets, sécurité, logistique)",
      source: "Auto-déclaration Tate",
      context: "Prouve le coût de la mobilité premium et de la sécurité personnelle à haut niveau",
      visual: "count-up",
    },
    {
      number: "$5M",
      label: "Investissement fait en 15 minutes suite à un message War Room",
      source: "Auto-déclaration Tate",
      context: "Illustre la vitesse décisionnelle possible dans un network prédateur",
      visual: "count-up",
    },
    {
      number: "5",
      label: "Nombre de personnes qui définissent statistiquement ta trajectoire",
      source: "Aphorisme popularisé par Jim Rohn — soutenu partiellement par études Christakis & Fowler (2007)",
      context: "Fondement de l'audit du network",
      visual: "count-up",
    },
    {
      number: "18h",
      label: "Heures de travail quotidien revendiquées par Tate (phase active income)",
      source: "Auto-déclaration Tate",
      context: "Argument sur la saturation temporelle avant tout passif",
      visual: "bar",
    },
    {
      number: "2h30",
      label: "Temps pris pour écrire son morceau musical viral (vs 6 mois pour son ami)",
      source: "Anecdote Tate",
      context: "Preuve emblème de la doctrine speed",
      visual: "comparison",
    },
    {
      number: "3 sem",
      label: "Délai après le premier 4-minute mile de Bannister avant que 10 autres le fassent",
      source: "Histoire vérifiée (1954)",
      context: "Preuve empirique du plafond mental",
      visual: "count-up",
    },
    {
      number: "10-11M$",
      label: "Argent perdu par Tate suite aux fermetures de comptes bancaires (Matrix attack)",
      source: "Auto-déclaration Tate",
      context: "Utilisé comme preuve autobiographique du principe 100 % accountability",
      visual: "count-up",
    },
    {
      number: "$1M/an",
      label: "Ordre de grandeur du lifestyle 'top' revendiqué par Tate",
      source: "Auto-estimation Tate",
      context: "Point de référence financier pour cadrer les ambitions du lecteur",
      visual: "count-up",
    },
    {
      number: "43%",
      label: "Part de la richesse mondiale détenue par le top 1 % (2023)",
      source: "Rapport Oxfam / Credit Suisse Global Wealth 2023",
      context: "Contextualise l'argument anti-redistribution : les asset owners captent effectivement le stimulus",
      visual: "percent",
    },
    {
      number: "$1000",
      label: "Stimulus check hypothétique par UK citizen — finit majoritairement chez Amazon/Bezos",
      source: "Expérience de pensée Tate — cohérente avec analyse Fed sur Covid stimulus checks",
      context: "Prouve que la redistribution simple ne redistribue pas structurellement",
      visual: "comparison",
    },
  ],

  comparisons: [
    {
      title: "Feather vs Conqueror (Forrest Gump)",
      left: { label: "Feather (majorité)", items: ["La vie te pousse", "Tu es sujet aux circonstances", "Le vent décide", "Bonheur passif si chance", "Écroulement en crise"] },
      right: { label: "Conqueror (Tate)", items: ["Tu happens to life", "Tu es la circonstance", "Tu décides du vent", "Purpose actif construit", "Levier même en crise"] },
    },
    {
      title: "Active vs Passive Income (ordre correct)",
      left: { label: "Étape 1 : Active", items: ["Vends du temps direct", "Commission only assumée", "18h/j saturés", "Pas de romantisation du passif", "Signal : je bosse"] },
      right: { label: "Étape 2 : Passive", items: ["Une fois active saturé", "Systèmes + staff", "Buying freedom pas rich", "Levier > effort direct", "Signal : je scale"] },
    },
    {
      title: "Reading vs Doing",
      left: { label: "Lecture-refuge", items: ["8h dans un livre", "Reward without risk", "Illusion de progrès", "Aucun test réel", "Simulation de compétence"] },
      right: { label: "Action-preuve", items: ["30 min pour armer 1 décision", "Test dans le réel immédiat", "Feedback dur", "Compétence prouvée", "Confiance ← résultats"] },
    },
    {
      title: "Fun (mode féminin) vs Purpose (mode masculin selon Tate)",
      left: { label: "Fun (Tate)", items: ["Recevoir de l'expérience", "Consommer", "Court terme", "Sensation immédiate", "Ignorance protégée"] },
      right: { label: "Purpose (Tate)", items: ["Créer de l'expérience", "Construire", "Long terme", "Conquête cumulée", "Compétence lucide"] },
    },
    {
      title: "Weak Man vs Stoic Man (retournement civique)",
      left: { label: "Weak Man", items: ["Émotions dictent l'action", "Impulsivité destructrice", "Violence conjugale, rixes", "Fire uncontrolled", "Danger pour autrui"] },
      right: { label: "Stoic Man", items: ["Décision > émotion", "Contrôle opératif", "Neutralité fonctionnelle", "Fire channeled", "Service à la civilisation"] },
    },
    {
      title: "Money as Rich vs Money as Free",
      left: { label: "Buying Rich", items: ["Consommation ostentatoire", "Signaling social", "Objets dépréciables", "Piège de la course", "Peur du niveau au-dessus"] },
      right: { label: "Buying Free", items: ["Sécurité personnelle", "Liberté géographique", "Absence de peur", "Power = protection", "Détachement du niveau"] },
    },
    {
      title: "Isolated Man vs Networked Man (War Room)",
      left: { label: "Isolé", items: ["Lit un livre 8h", "Décisions lentes", "Aucune opportunité entrante", "Idées non-testées", "Perd par défaut"] },
      right: { label: "Networked", items: ["25 messages au réveil", "Décisions en 15 min", "Opportunités constantes", "Idées calibrées par pairs", "Gagne par défaut"] },
    },
  ],

  // ============================================================
  // 8. RHETORICAL DEVICES
  // ============================================================
  devices: [
    {
      name: "Aphorisme d'attaque",
      example_text: "You're too slow and you are going to lose against people like me.",
      effect: "Ancrage brutal + provocation",
      why_it_works: "Court, sans excuse, force à répondre mentalement — donc à s'engager dans la conversation intérieure",
    },
    {
      name: "Anaphore",
      example_text: "This is my fault. All of this is me. I got here. It's my fault.",
      effect: "Saturation de la responsabilité",
      why_it_works: "La répétition transforme une position mentale (assumer) en une identité (je suis celui qui assume)",
    },
    {
      name: "Chiasme rhétorique",
      example_text: "You can't let life come to you. You have to come to life.",
      effect: "Renversement sémantique mémorable",
      why_it_works: "La structure croisée grave la formule dans la mémoire — inversion de rôle instantanément visible",
    },
    {
      name: "Analogie mythique",
      example_text: "Forrest is the feather and life has just pushed him all over. — Bad things happened to Batman. That's why he's Batman.",
      effect: "Rendre visible un modèle mental via un référent partagé",
      why_it_works: "Utilise des héros populaires que le public connaît — court-circuite la contestation abstraite",
    },
    {
      name: "Question rhétorique de retournement",
      example_text: "Why do you want me to believe this? Is it because it's good for me or because it's good for you?",
      effect: "Retourner l'accusateur — ne pas réfuter la thèse mais interroger le motif",
      why_it_works: "Déplace le débat du contenu vers l'intention. Impossible à réfuter frontalement.",
    },
    {
      name: "Auto-désignation à la 3e personne",
      example_text: "Tate arrives and circumstances change.",
      effect: "Mythification de soi + auto-preuve",
      why_it_works: "Parler de soi à la 3e personne fabrique une distance héroïque — Tate devient un personnage narratif",
    },
    {
      name: "Anecdote comme preuve (auto-biographique)",
      example_text: "I made a song in 2 and 1/2 hours. When they closed my bank accounts I lost 10 million dollars.",
      effect: "Rendre concret l'abstrait",
      why_it_works: "L'exemple vécu vaut mille théorèmes. Le vécu est incontestable structurellement.",
    },
    {
      name: "Insulte calibrée en clôture",
      example_text: "Dummies. Brokies. Get up off your ass.",
      effect: "Signal de camp — force le lecteur à choisir",
      why_it_works: "L'insulte n'est pas gratuite : elle ferme la porte de sortie sympathique et signale une identité tribale",
    },
    {
      name: "Reframe sémantique",
      example_text: "Reading a book is a reward without any risk.",
      effect: "Attaquer une vertu bourgeoise en la retournant",
      why_it_works: "Prend le prestige de l'objet (le livre) et le retourne comme faiblesse. Force à défendre ce qu'on croyait acquis.",
    },
    {
      name: "Paradoxe reformulateur",
      example_text: "The best things ever happened to me are the worst things ever happened to me.",
      effect: "Choc cognitif — réorganise instantanément la biographie",
      why_it_works: "Le paradoxe force le cerveau à chercher une résolution — et la résolution offerte réoriente toute la vie passée",
    },
    {
      name: "Impératif catégorique",
      example_text: "Get up off your ass and work first. Choose your character and build it.",
      effect: "Ordre direct sans échappatoire",
      why_it_works: "Court-circuite la délibération. L'impératif appelle une réponse binaire : obéir ou refuser explicitement.",
    },
    {
      name: "Gradation d'exemples concrets",
      example_text: "You can conquer the sky by building a skyscraper. You can conquer by building roads. You can conquer by having a beautiful family and children.",
      effect: "Élargir un concept abstrait à des applications visibles",
      why_it_works: "L'énumération concrète transforme un mot ambigu (conquer) en champ d'action reconnaissable",
    },
    {
      name: "Auto-preuve par intensité",
      example_text: "I'll be reading what I need to read and on the phone and playing chess at the same time. Otherwise, my brain's not full.",
      effect: "Auto-portrait de l'exigence portée en identité",
      why_it_works: "Rend visible que ce dont il parle, il le vit — la preuve du principe est son propre corps en action",
    },
    {
      name: "Corrélation inversée provocante",
      example_text: "Your ability to speak freely is directly correlated to your insignificance.",
      effect: "Réordonner intuitivement un rapport supposé",
      why_it_works: "Renverse la doxa (les puissants parlent librement) et force à repenser le rapport pouvoir/parole",
    },
    {
      name: "Contraste énumératif",
      example_text: "We don't talk about Rihanna, football, Love Island. We only talk about money.",
      effect: "Rendre visible un filtre par ce qu'il exclut",
      why_it_works: "Nommer ce qu'on rejette produit l'image du champ occupé — le vide définit le plein",
    },
    {
      name: "Frame vidéo-jeu",
      example_text: "Choose your character and build it.",
      effect: "Ludifier la construction de soi",
      why_it_works: "Le référent RPG rend l'auto-construction accessible et concrète — chaque décision devient un stat point",
    },
  ],

  // ============================================================
  // 9. ANALOGIES & EXAMPLES
  // ============================================================
  analogies: [
    {
      source: "Chess (jeu d'échecs)",
      used_for: "Justifier le 100 % accountability — aucune chance, chaque défaite diagnosticable",
      strength: 9,
      why_it_works: "Modèle fermé et pur : impossible d'invoquer la chance. Transposé à la vie, cadre puissant de leviérage.",
    },
    {
      source: "Forrest Gump feather",
      used_for: "Illustrer les deux ontologies : plume portée par le vent vs vent lui-même",
      strength: 10,
      why_it_works: "Image cinéma que tout le monde a vue sans l'avoir décodée. Le décodage semble être une révélation, pas une thèse.",
    },
    {
      source: "Batman & ses parents",
      used_for: "Théodicée du trauma — sans les parents morts, pas de Batman",
      strength: 10,
      why_it_works: "Héros populaire universel. Personne ne remet en question que Batman devait souffrir pour devenir Batman. Transféré à la biographie du lecteur.",
    },
    {
      source: "Ferrari (3,2 M$)",
      used_for: "Illustrer le seuil où l'argent devient irréel",
      strength: 7,
      why_it_works: "Objet iconique du luxe absolu. Le chiffre choc + l'objet reconnu produisent une image mentale forte du niveau visé.",
    },
    {
      source: "4-minute mile (Roger Bannister)",
      used_for: "Prouver que la barrière est mentale, pas biologique",
      strength: 9,
      why_it_works: "Fait historique vérifiable + résultat mesurable + réplication rapide (10 personnes en 3 semaines) = preuve difficile à réfuter.",
    },
    {
      source: "Coffee shop décodage",
      used_for: "Frame mental permanent d'idéation business",
      strength: 8,
      why_it_works: "Situation banale que tout le monde vit — le retournement 'chaque café est un cours business gratuit' transforme le quotidien en salle de classe.",
    },
    {
      source: "Le musicien qui ne finit pas son album (6 mois de perfection)",
      used_for: "Illustrer la lenteur déguisée en perfection",
      strength: 8,
      why_it_works: "Archétype reconnaissable (l'ami perfectionniste qui n'accouche jamais). Rend visible un piège concret.",
    },
    {
      source: "War Room network (25 messages au réveil, deal 5M$)",
      used_for: "Illustrer la puissance du network prédateur",
      strength: 9,
      why_it_works: "Contraste dramatique entre la vie isolée (8h de livre) et la vie networkée (15 min pour 5M$) — visualisation immédiate.",
    },
    {
      source: "Feather → Batman (méta-analogie)",
      used_for: "Passage de la position passive à la position transformatrice de la douleur",
      strength: 9,
      why_it_works: "Deux héros cinéma : l'un est ballotté (Forrest), l'autre transmute (Batman). L'arc entier de la doctrine tient dans ces deux images.",
    },
    {
      source: "Kickboxing coach / Mike Tyson te dit que tu ne sais pas boxer",
      used_for: "Ego vs learning — tu ne deviens pas maître sans être bon élève",
      strength: 8,
      why_it_works: "Autorité expérientielle indiscutable (personne ne conteste Mike Tyson en boxe) — force à admettre le rapport maître-élève",
    },
  ],

  // ============================================================
  // 10. OPERATIONAL FRAMEWORKS
  // ============================================================
  frameworks: [
    {
      name: "Protocole 100 % Accountability (F1)",
      when_to_use: "Face à chaque contrariété, injustice, échec professionnel ou personnel",
      steps: [
        "Écrire l'événement en 1 phrase factuelle (pas interprétative)",
        "Écrire 3 causes possibles où *tu* es responsable — même si c'est faux à 90 %",
        "Pour chaque cause, écrire 1 action de leviérage possible",
        "Choisir l'action à plus haut ROI",
        "L'exécuter dans les 24h",
        "Journaliser le résultat 7 jours plus tard",
      ],
      warning: "C'est un outil de leviérage, PAS un jugement moral. Ne pas appliquer sur les victimes réelles d'agressions ou d'injustices structurelles.",
    },
    {
      name: "Test des 3 heures / Speed drill (F2)",
      when_to_use: "Quand tu diffères depuis > 2 semaines une tâche que tu prétends 'complexe'",
      steps: [
        "Choisir la tâche différée",
        "Bloquer 3 heures continues sans interruption (téléphone en avion)",
        "S'engager à livrer *quelque chose de fini* — imparfait mais complet",
        "À la fin des 3h, publier / envoyer / présenter le résultat",
        "Comparer le résultat effectif à ta prévision initiale",
        "Répéter chaque semaine avec 1 nouvelle tâche",
      ],
      warning: "Le fait qu'un truc puisse être fait en 3h ne veut pas dire qu'il *doive* toujours l'être. Applicable aux blocages, pas aux projets stratégiques.",
    },
    {
      name: "Trio de progression financière (F3)",
      when_to_use: "Diagnostic annuel de ta phase financière — quelle étape es-tu en train de brûler ou de sauter ?",
      steps: [
        "Étape 1 : active income max — vends ton temps direct jusqu'à 90 % saturé",
        "Étape 2 : passivation partielle — système + staff, une fois le temps saturé",
        "Étape 3 : buying freedom — l'argent achète de la protection et du levier, pas des Ferraris",
        "Interdit : sauter directement de 1 à 3 en imaginant du passif inexistant",
        "Marker de progression : à quelle heure tu te lèves + combien de temps tu passes à optimiser vs à faire",
      ],
      warning: "Passer à l'étape n+1 seulement quand l'étape n est saturée. Sinon retour en arrière garanti.",
    },
    {
      name: "Audit du network 5-personnes (F4)",
      when_to_use: "Chaque trimestre, ou en cas de sensation de stagnation malgré effort",
      steps: [
        "Liste les 5 personnes avec qui tu as passé le plus d'heures ce trimestre",
        "Note pour chacune : niveau dans ton domaine (>toi / =toi / <toi) + trajectoire (montante / plate / descendante)",
        "Colonne cible : combien d'heures leur donner le trimestre suivant",
        "Décision : couper les descendantes de -50 %, doubler les montantes, chercher activement 1 personne au-dessus de toi",
        "Refaire l'audit 90 jours plus tard",
      ],
      warning: "Ne pas confondre 'couper le temps' avec 'trahir'. Le lien peut rester à basse fréquence. Ne pas appliquer aux liens familiaux vitaux.",
    },
    {
      name: "Coffee Shop Mental Exercise (F5)",
      when_to_use: "Chaque fois que tu dépenses > 5 € dans un commerce",
      steps: [
        "Ouvrir un carnet dédié (papier ou app)",
        "Noter : le produit + le prix payé + estimation coût de production",
        "Estimer la marge et le volume mensuel du commerce",
        "Écrire 1 amélioration possible ou 1 variante que tu aurais faite mieux",
        "Objectif après 3 mois : 100 pages = 100 opportunités identifiées",
        "Choisir 1 opportunité tous les 90 jours et la tester en side-project",
      ],
      warning: "L'exercice génère beaucoup d'idées. Le piège = ne jamais en tester une. Discipliner à en tester 1 tous les 90 jours minimum.",
    },
    {
      name: "Trauma Reframing (F6)",
      when_to_use: "Face à un événement passé qui produit encore de la charge émotionnelle négative",
      steps: [
        "Identifier la période la plus dure de ta vie (une seule)",
        "Colonne 1 : 3 compétences acquises grâce à elle",
        "Colonne 2 : 3 traits de caractère forgés",
        "Colonne 3 : 3 relations gagnées ou définitivement clarifiées",
        "Interdit : laisser une case vide (chercher jusqu'à trouver)",
        "Reformuler cette période en 1 phrase : 'c'est la fondation de qui je suis parce que...'",
      ],
      warning: "Ne pas appliquer aux traumas cliniques non traités (PTSD, abus prolongé). Ces derniers exigent un travail thérapeutique en amont. Le reframing est un outil de finition, pas de premier soin.",
    },
    {
      name: "Le test du 0,25 s (F7)",
      when_to_use: "Avant de développer tout produit, contenu, pitch",
      steps: [
        "Écrire ton hook (1 phrase / 1 image)",
        "Le tester : afficher devant 5 personnes pendant 0,25 s (montre-le au vol)",
        "Leur demander ce qu'elles ont retenu",
        "Si 4/5 ont retenu l'idée-clé : ok",
        "Sinon, retravailler le hook AVANT de développer le reste",
        "Ne construire le produit qu'une fois le hook validé",
      ],
      warning: "Le hook fort sans substance derrière = clickbait qui brûle ta crédibilité. Le hook fort avec substance = leader.",
    },
    {
      name: "Reframe du stress (F8)",
      when_to_use: "À chaque poussée de cortisol / stress ressenti",
      steps: [
        "Détecter la sensation physique de stress (tension épaules, respiration courte)",
        "Nommer intérieurement : 'mon cerveau s'allume' (au lieu de 'je vais craquer')",
        "Respirer 3 fois profondément",
        "Passer à l'action prévue en gardant le récit 'fuel'",
        "Le soir, journaliser : quelles décisions le stress a-t-il aidé aujourd'hui ?",
        "Répéter 21 jours pour ancrer",
      ],
      warning: "Ne pas confondre avec le déni. Un stress chronique élevé sur > 6 mois exige un vrai check médical.",
    },
  ],

  // ============================================================
  // 11. DRILLS
  // ============================================================
  drills: [
    {
      name: "Journal 100 % accountability (30 jours)",
      duration: "30 jours",
      instructions: [
        "Chaque soir, écrire 3 contrariétés de la journée",
        "Pour chacune : 'Comment ai-je créé cela ?' — même si la réponse semble injuste",
        "Interdit de blâmer autrui, même quand la faute est objectivement chez autrui",
        "Objectif : entraîner le muscle du levier, pas la culpabilité",
        "À J30 : relire les 90 entrées et identifier les 3 pattern récurrents",
      ],
      difficulty: 3,
    },
    {
      name: "Règle des 3 heures (hebdomadaire)",
      duration: "12 semaines",
      instructions: [
        "Chaque lundi, choisir 1 tâche différée depuis > 2 semaines",
        "Bloquer 3 heures sans interruption (jeudi 9h-12h par défaut)",
        "Livrer *quelque chose* à J+7 — imparfait mais fini",
        "Comparer résultat à prévision initiale",
        "Après 12 semaines : 12 tâches libérées, calibrage de ton estimateur interne",
      ],
      difficulty: 3,
    },
    {
      name: "Audit hebdo network + réallocation",
      duration: "8 semaines",
      instructions: [
        "Chaque dimanche : 'Cette semaine, avec qui ai-je passé le plus d'heures ?'",
        "Répondre honnêtement, avec les vraies heures",
        "Marquer trajectoire de chaque personne (montante/plate/descendante)",
        "Cette semaine à venir : réallouer 5h d'une relation descendante vers 1 montante",
        "Après 8 semaines : audit du delta d'énergie mentale",
      ],
      difficulty: 4,
    },
    {
      name: "Coffee Shop Notebook (90 jours)",
      duration: "90 jours",
      instructions: [
        "Carnet dédié (papier de préférence)",
        "Chaque dépense > 5 € = une entrée (coût / marge / amélioration)",
        "Une seule règle : jamais un jour sans entrée",
        "À J90 : sélectionner les 3 meilleures idées",
        "Choisir 1 à tester en side project pendant le trimestre suivant",
      ],
      difficulty: 2,
    },
    {
      name: "Le rechannel du stress (21 jours)",
      duration: "21 jours",
      instructions: [
        "À chaque poussée de stress, dire mentalement 'mon cerveau s'allume'",
        "Observer les changements sur sommeil, décisions, performance",
        "Journaliser 3 lignes par soir (stress ressenti / recadrage / résultat)",
        "À J21 : évaluation qualitative des changements",
      ],
      difficulty: 2,
    },
    {
      name: "Le test 'so what?' (30 jours)",
      duration: "30 jours",
      instructions: [
        "Face à toute émotion invalidante (peur, gêne, honte), poser mentalement 'et alors ?'",
        "Exécuter l'action prévue quand même",
        "Répéter — objectif : habituer le circuit de contournement émotionnel",
        "À J30 : mesure du nombre de fois où 'so what?' a permis d'agir",
      ],
      difficulty: 3,
    },
    {
      name: "L'exercice du 4-minute mile",
      duration: "30 jours",
      instructions: [
        "Écrire un objectif que tu juges 'impossible' pour toi",
        "Trouver 3 personnes comparables (même background) qui l'ont fait",
        "Étudier leur trajectoire — noter les 3 étapes-clés",
        "Agir 30 jours *comme si* tu l'avais déjà atteint (posture, décisions, mots)",
        "Comparer résultat à 30 jours vs. posture 'c'est dur'",
      ],
      difficulty: 4,
    },
  ],

  // ============================================================
  // 12. RELATED CONTENT
  // ============================================================
  related: {
    videos: [
      "LFJAHZlizAg", // Never Tired When Winning — doctrine dépression / winning
      "AG1vvPVkHC8", // Raw action solves all — complément à cause vs effet
      "d8FH8K7n0GE", // Live for something bigger — complément à la doctrine du purpose
      "Gv39IoU5Z5s", // Educate yourself daily — complément speed + information
      "KPbnzSGlAP4", // Complément corpus Tate
    ],
    debates: [
      "masculinite-feminisme", // Croiser les affirmations sur homme/femme
      "rhetorique-verites-difficiles", // Étudier le pattern rhétorique des vérités dures
    ],
  },
};

// Register into global registry
if (typeof CONTENT_REGISTRY !== 'undefined') CONTENT_REGISTRY["P4rkjwaa6so"] = CONTENT_P4rkjwaa6so;
